Adaugă conținut pentru capitolul "Îmbunătățirea lucrului în linia de comandă"
Sergiu121/uso-lab-book pull request #13
Opened 2020-08-11 22:05 UTC by edi33416

Mai e mult până departe

Signed-off-by: Eduard Staniloiu <edi33416@gmail.com>

2020-08-11 22:06 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/13/merge

2020-08-12 08:48 UTC, CostinCarabas requested changes

2020-08-12 08:48 UTC, CostinCarabas commented on chapters/improve-cli/improve-terminal.rst
> +Principalul atu al utilizării aplicațiilor în linie de comandă, și nu în mediul grafic, îl reprezintă viteza cu care rezolvăm anumite task-uri.
s/task-uri/sarcini/g ?

2020-08-12 08:48 UTC, CostinCarabas commented on chapters/improve-cli/improve-terminal.rst
> +Întotdeauna ne dorim să fim mai rapizi și să automatizăm cât mai mult din sarcinile noastre pentru că cu cât ne terminăm treaba mai repede, cu atât avem mai mult timp liber la dispoziție.
s/pentru că/deoarece/g ?

2020-08-12 08:48 UTC, CostinCarabas commented on chapters/improve-cli/improve-terminal.rst
> +Un astfel de scenariu este dat de dezvoltarea aplicațiilor, scenariu pe care îl putem sparge în trei componente (sub-taskuri): scrierea aplicației, compilarea aplicației și testarea aplicației.
s/sub-taskuri/sub-sarcini/g  sună ciudat? Dacă da, s/sub-taskuri/sub-task-uri/g cred că este mai corect.

2020-08-12 08:48 UTC, CostinCarabas commented on chapters/improve-cli/improve-terminal.rst
> +Acum structura este mai "curată" și am păstrat separarea logică: în primul tab vom scrie aplicația, în cel de-al doilea tab o vom compila și în ultimul tab (al treilea) o vom rula.
s/rula/executa/g

2020-08-12 08:48 UTC, CostinCarabas commented on chapters/improve-cli/improve-terminal.rst
> +Separarea logică în fereastră per task și tab per sub-task este benefică atunci când vă ocupați concomitent de mai multe lucruri.
s/task/sarcină/g

2020-08-12 08:48 UTC, CostinCarabas commented on chapters/improve-cli/improve-terminal.rst
> +Puteți folosi exercițiile de la dezvoltarea aplicațiilor ca suport pentru spargerea în taskuri și sub-taskuri.
s/taskuri/sarcini/g

2020-08-12 08:48 UTC, CostinCarabas commented on chapters/improve-cli/improve-terminal.rst
> +* Navigat în interiorul unei comenzi (ctrl+a, ctrl+e, alt+f, alt+b), modificări (ctrl+k, ctrl+u, alt+d) și paste (ctrl+y)
**s/ctrl/Ctrl/g** și **s/alt/Alt/g** pentru consistență.

2020-08-12 08:59 UTC, edi33416 commented on chapters/improve-cli/improve-terminal.rst
> +Un astfel de scenariu este dat de dezvoltarea aplicațiilor, scenariu pe care îl putem sparge în trei componente (sub-taskuri): scrierea aplicației, compilarea aplicației și testarea aplicației.
Parcă sună mai bine sub-task-uri? @lizababu tu ce zici?

2020-08-12 09:02 UTC, edi33416 commented on chapters/improve-cli/improve-terminal.rst
> +Separarea logică în fereastră per task și tab per sub-task este benefică atunci când vă ocupați concomitent de mai multe lucruri.
Aici implică și modificarea din sub-task în sub-sarcină. Odată ce ne decidem cum rămâne, sub-task sau sub-sarcină, modific peste tot.

2020-08-12 09:02 UTC, edi33416 commented on chapters/improve-cli/improve-terminal.rst
> +Puteți folosi exercițiile de la dezvoltarea aplicațiilor ca suport pentru spargerea în taskuri și sub-taskuri.
Ditto

2020-08-12 09:03 UTC, edi33416 commented on chapters/improve-cli/improve-terminal.rst
> +* Navigat în interiorul unei comenzi (ctrl+a, ctrl+e, alt+f, alt+b), modificări (ctrl+k, ctrl+u, alt+d) și paste (ctrl+y)
Acum îl scriu

2020-08-12 11:12 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/13/merge

2020-08-12 11:58 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/13/merge

2020-08-13 13:55 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/13/merge

2020-08-16 15:08 UTC, lizababu commented on chapters/improve-cli/improve-terminal.rst
> +Un astfel de scenariu este dat de dezvoltarea aplicațiilor, scenariu pe care îl putem sparge în trei componente (sub-taskuri): scrierea aplicației, compilarea aplicației și testarea aplicației.
Și eu parcă inclin spre "task" în loc de "sarcină". Nu știu cum e corect sincer (dacă sub-task-uri sau sub-taskuri). Din mesajul lui @razvand `Legat de cum articulăm substantivele venite din limba engleză: https://www.stefamedia.com/englezisme-anglicisme-articulate-cu-sau-fara-cratima/
Deci bufferul, serverul, targetul, Internetul, linkul, Washingtonul, headingul, bulletul, commitul. Dar show-ul, Bruxelles-ul, hobby-ul, branch-ul.` pare că "taskuri" e corect. Voi ce părere aveți?

2020-08-17 06:05 UTC, lizababu requested changes
Am lăsat câteva comentarii de formă, în general legate de screenshot-uri per window, code-block pe unde e nevoie, câteva typo-uri, câteva adăugiri.

2020-08-17 06:05 UTC, lizababu commented on chapters/improve-cli/improve-terminal.rst
>  * Pornirea mai multor instanțe de shell în aceelași terminal. Comanda exit și shortcut-ul ctrl+d
Astea sunt un fel de "cu astea rămânem după ce citim această pagină"?

2020-08-17 06:05 UTC, lizababu commented on chapters/improve-cli/improve-terminal.rst
> +.. image:: img/settings-keyboard-shortcuts.png
Screenshot window (dacă ai făcut așa, scuze, dar mă enervează marginea :)) )

2020-08-17 06:05 UTC, lizababu commented on chapters/improve-cli/improve-terminal.rst
> +.. image:: img/hello-multi-tabs.png
Screenshot window

2020-08-17 06:05 UTC, lizababu commented on chapters/improve-cli/improve-terminal.rst
> +.. image:: img/tab-completion.png
Și aici cred că merge code-block (că nu mai contează cum arată taburile sau terminalele pe ecran)

2020-08-18 11:01 UTC, edi33416 commented on chapters/improve-cli/improve-terminal.rst
> +Astfel, ferestrele din sistem vor arăta similar cu imaginea de mai jos:
Eu sunt pentru `:`. O să las așa deocamdată. Dacă sunt preferințe puternice pentru `.` o să modific

2020-08-18 11:02 UTC, edi33416 commented on chapters/improve-cli/improve-terminal.rst
> +Pentru a vedea scurtăturile disponibile la nivel de sistem, și pentru a defini noi scurtături, pe distribuțiile **Ubuntu** accesați *Settings* -> *Devices* -> *Keyboards* -> *Keyboard Shortcuts* din
Am scris mai jos

2020-08-18 11:02 UTC, edi33416 commented on chapters/improve-cli/improve-terminal.rst
> +.. image:: img/hello-multi-terms.png
😆

2020-08-18 12:00 UTC, edi33416 commented on chapters/improve-cli/improve-terminal.rst
> +Încercați.
Nu prea ai ce exercițiu să faci aici. Dacă fac bine, dacă nu iarăși bine :)))

2020-08-18 20:46 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/13/merge

2020-08-19 15:08 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/13/merge

2020-08-19 16:30 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/13/merge

2020-09-01 15:09 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/13/merge

2020-09-01 15:36 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/13/merge

2020-09-02 13:52 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/13/merge

2020-09-09 12:19 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/13/merge

2020-09-09 12:25 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/13/merge

2020-09-09 12:36 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/13/merge

2020-09-26 08:04 UTC, CostinCarabas approved these changes

2020-09-26 08:04 UTC, CostinCarabas commented on chapters/improve-cli/inspect-fs.rst
> +Exersarea navigării în cardul sistemului de fișiere
cadrul

2020-09-26 08:04 UTC, CostinCarabas commented on chapters/improve-cli/inspect-fs.rst
> +Afișarea informațiilor extinse despre fișiere
Informațiile de aici (fișiere ascunse, info extinse despre fișiere) ar trebui să le pun și eu, doar eu sau doar tu?

2020-10-12 09:13 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/13/merge

2020-11-06 22:21 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/13/merge

2020-11-08 13:09 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/13/merge

2020-11-09 10:40 UTC, CostinCarabas requested changes

2020-11-09 10:40 UTC, CostinCarabas commented on chapters/improve-cli/improve-shell.rst
> +* Operatorul ``;`` - este folosit pentru separarea comenzilor, dar nu ține cont dacă comenzile anterioare au fost executate cu succes sau nu.
Poți să pui un exemplu în care merge prima oară și apoi exemplul ăsta.

2020-11-09 10:40 UTC, CostinCarabas commented on chapters/improve-cli/improve-shell.rst
> +    În cazul în care fișierul destinație nu există, operatorul ``>`` în va crea.
în -> îl

2020-11-09 10:40 UTC, CostinCarabas commented on chapters/improve-cli/improve-shell.rst
> +Am scris, prin încercări succesive, onelinerul care ne afișează primele zece procese care consumă cea mai multă memorie.
Știu ce este un **onelinerul**?

2020-11-09 10:40 UTC, CostinCarabas commented on chapters/improve-cli/improve-shell.rst
> +** Exercițiu**: Folosiți fișierul generat și utilitarul ``tar`` pentru a testa diferite metode de compresie a arhivelor.
Nu este afișat corect.

2020-11-09 10:40 UTC, CostinCarabas commented on chapters/improve-cli/improve-shell.rst
> +Comparați dimensiunile arhivelor opținute.
opținute -> obținute

2020-11-09 12:29 UTC, lizababu requested changes
Aș uni toate secțiunile "Sumar" într-o secțiune "Cheatsheet".
Să nu uiți să pui ref la toate secțiunile și subsecțiunile.

2020-11-09 12:29 UTC, lizababu commented on chapters/improve-cli/improve-shell.rst
> +O astfel de înlănțuire de comenzi este numită oneliner.
**oneliner** (cu bold) + un footnote cu o explicație mai amplă (toată discuția că dacă are ; în ea nu e oneliner)

2020-11-09 12:29 UTC, lizababu commented on chapters/improve-cli/improve-shell.rst
> +    -rw------- 1 student student    10992 nov  6 14:56 ./.ICEauthority
eu n-am folosit xargs ăsta până acum; pare a fi potrivit să fie prezentat într-un capitol de shell scripting

2020-11-09 12:29 UTC, lizababu commented on chapters/improve-cli/improve-shell.rst
> +Redirectări
menționează că s-a mai vorbit de asta în capitolul Lucrul cu fișiere

2020-11-09 12:29 UTC, lizababu commented on chapters/improve-cli/improve-shell.rst
> +* **STDERR** are asociat descriptorul de fișier 2
nu cred că e important acum să știe ce e un fd, că avem numerele astea; în afară de 2> nu mai înseamnă nimic pentru ei

2020-11-09 12:29 UTC, lizababu commented on chapters/improve-cli/improve-shell.rst
> +Folosim operatorul ``>`` pentru a redirecta **STDOUT** sau **STDERR** într-un fișier.
cred că e mai ușor de înțeles dacă spui că avem <, > și 2> și nu că avem > care e de fapt 1> sau 2> cum e zis mai jos
după apare întrebarea de ce nu folosim 0>

2020-11-09 12:29 UTC, lizababu commented on chapters/improve-cli/improve-shell.rst
> +Folosim operatorul ``>`` pentru a redirecta **STDOUT** sau **STDERR** într-un fișier.
mai ales că până acum 1> n-a mai fost folosit, peste tot a fost ">"

2020-11-09 12:29 UTC, lizababu commented on chapters/improve-cli/improve-shell.rst
> +    student@uso:~$ ps -aux --sort=-%mem | head -11
bsd -> standard

2020-11-09 12:29 UTC, lizababu commented on chapters/improve-cli/improve-shell.rst
> +Am scris, prin încercări succesive, onelinerul care ne afișează primele zece procese care consumă cea mai multă memorie.
era scris mai sus, am lăsat eu un comentariu să detalieze puțin, dar într-un footnote

2020-11-09 12:29 UTC, lizababu commented on chapters/improve-cli/improve-shell.rst
> +Am scris, prin încercări succesive, onelinerul care ne afișează primele zece procese care consumă cea mai multă memorie.
spune că ai folosit comanda aia în nu mai știu care secțiune ca să poată merge acolo la nevoie

2020-11-09 12:29 UTC, lizababu commented on chapters/improve-cli/improve-shell.rst
> +* Fișierul ``/dev/zero`` este un generator de octeți.
precizează undeva, un footnote, că valoarea 0 nu înseamnă cifra 0

2020-11-09 12:29 UTC, lizababu commented on chapters/improve-cli/improve-shell.rst
> +  **Exercițiu**: Rulați comanda ``cat /dev/zero`` pentru a înțelege nevoia utilitarului ``xxd`` din exemplul de mai sus.
trebuie să explici tu; nu o să înțeleagă de ce nu afișează nimic; nu au asocierea bine în minte că ăla e caracter nul, nu e printabil, din astea

2020-11-09 12:29 UTC, lizababu commented on chapters/improve-cli/improve-shell.rst
> +  Trecem rezultatul lui ``cat`` prin ``xxd`` deoarece valoarea **0** nu este un caracter print-abil.
printabil

2020-11-09 12:29 UTC, lizababu commented on chapters/improve-cli/improve-shell.rst
> +  Trecem rezultatul lui ``cat`` prin ``xxd`` deoarece valoarea **0** nu este un caracter print-abil.
sau dacă vrei: nu este un caracter obișnuit, ca cele de pe tastatură deoarece nu are un echivalent grafic
o chestie în genul ăsta poate

2020-11-09 12:29 UTC, lizababu commented on chapters/improve-cli/improve-shell.rst
> +Generatoarele de octeți sunt utile pentru a testa aplicațiile pe care le dezvoltăm pe inputuri random.
asta e valabil doar pentru /dev/urandom și oricum nu înseamnă nimic pentru ei; ce-i ăla input random? de ce au nevoie de așa ceva?

2020-11-09 12:29 UTC, lizababu commented on chapters/improve-cli/improve-terminal.rst
> +Sumar: Scurtături în terminal
la fel, în secțiune de cheatsheet

2020-11-09 12:36 UTC, edi33416 commented on chapters/improve-cli/improve-terminal.rst
> +Funcția de auto-complete este extrem de utilă și îmbunătățește în mod dramatic viteza cu care realizăm acțiuni în terminal.
nici nu încercam să fiu funny :))))

2020-11-09 18:14 UTC, edi33416 commented on chapters/improve-cli/improve-terminal.rst
> +Pentru a naviga între instanțe ale aceleiași aplicații (ex. două terminale deschise în două ferestre diferite) putem folosi combinația de taste ``Alt+~``.
> Ai putea să specifici în plus: tastele Alt și ~(tilda) simultan.
Să nu considere și + ca parte din comandă.

Am adăugat, dar nu știu dacă aici trebuie menționat sau la începutul secțiunii.
Folosim ``tasta1+tasta2`` peste tot

2020-11-09 18:16 UTC, edi33416 commented on chapters/improve-cli/improve-terminal.rst
> +Prin simpla apăsare a tastei ``Tab`` în timp ce scriem numele unei comenzi, al unei opțiuni a unei comenzi sau calea către un director sau fișier, terminalul va completa în mod automat textul sau va
Dublă apăsare atunci când este ambiguu. Am clarificat

2020-11-09 18:16 UTC, edi33416 commented on chapters/improve-cli/improve-terminal.rst
> +.. code-block:: bash
o să pun GIF

2020-11-09 18:17 UTC, edi33416 commented on chapters/improve-cli/inspect-fs.rst
> +Afișarea informațiilor extinse despre fișiere
Cred că este ok ca reminder?

2020-11-09 18:19 UTC, edi33416 commented on chapters/improve-cli/improve-terminal.rst
> +În loc să scriem manual o cale către un nume foarte lung, care poate implică și escaparea unor caractere speciale, lăsăm tasta ``Tab`` să facă asta pentru noi.
Am șters

2020-11-09 18:24 UTC, edi33416 commented on chapters/improve-cli/inspect-fs.rst
> +Navigarea sistemului de fișiere: comanda ``cd``
deci scot tot ce este la `cd`, da?

2020-11-09 18:26 UTC, edi33416 commented on chapters/improve-cli/inspect-fs.rst
> +Explorarea sistemului de fișiere: comanda ``ls``
Scot prima parte (povestea de intro și "Afișarea fișierelor ascunse")?

2020-11-09 18:28 UTC, edi33416 commented on chapters/improve-cli/inspect-fs.rst
> +#. Vom începe cu prima coloană din exemplul de mai sus: ``drwxr-xr-x``.
Deci zboară de aici? Să înțeleg că din tot ce e la `ls` rămâne doar globbing?

2020-11-09 18:29 UTC, edi33416 commented on chapters/improve-cli/inspect-fs.rst
> +Sintaxa specială ``[]``
Eu aș lăsa.
@lizababu tu ce zici?

2020-11-09 18:29 UTC, edi33416 commented on chapters/improve-cli/inspect-fs.rst
> +Sintaxa specială ``{}``
Eu aș lăsa.
@lizababu tu ce zici?

2020-11-09 18:30 UTC, edi33416 commented on chapters/improve-cli/inspect-fs.rst
> +Folosirea ad-litteram a caracterelor speciale
O să mut `[]` și `{}` ca bonus.

2020-11-09 18:38 UTC, edi33416 commented on chapters/improve-cli/inspect-fs.rst
> +``file`` și ``touch``
Da, de aia nici n-am mai trecut ceva

2020-11-09 18:40 UTC, edi33416 commented on chapters/improve-cli/inspect-files.rst
> +#. Analizați, folosind ``less``, algoritmul de căutare din fișierul ``workspace/C/searching/linear_search.c``.
Ce anume să pun?

2020-11-09 20:38 UTC, edi33416 commented on chapters/improve-cli/improve-terminal.rst
> +.. note::
Tab îți scrie pe ecran. De la multe apăsări Tab ajungi să ai ecranul plin cu sugestii date de Tab și rezultatul ajunge să fie greu de observat / urmărit

2020-11-09 22:06 UTC, edi33416 commented on chapters/improve-cli/inspect-fs.rst
> +    student@uso:~$ find workspace/C -type f -name "*search*" -exec ls -l {} \;
Știu că o să caute pe Google, dar vreau să știe de existența ei, ca să ajungă să o caute

2020-11-09 22:12 UTC, edi33416 commented on chapters/improve-cli/inspect-files.rst
> +* TODO: bonus: reload (:Examine non_existing_file, ex. :e ee) - îl mai trec sau este prea mult / prea exoteric?
Așa dai reload dacă s-a modificat fișierul de când ai dat less. Și eu m-am gândit că e extraterestru.
De aia e lăsat ca TODO: ... ?
L-am scos

2020-11-09 22:18 UTC, edi33416 commented on chapters/improve-cli/inspect-files.rst
> +În cazul în care fișierele sunt identice, ``cmp`` nu afișează nimic pe ecran.
Este acolo: `cmp Documents/uso.tar Downloads/uso.tar`

2020-11-09 22:20 UTC, edi33416 commented on chapters/improve-cli/inspect-files.rst
> +^^^^^^^^^^^^^^^
nu-mi este clar ce să spun :))

2020-11-09 22:23 UTC, edi33416 commented on chapters/improve-cli/inspect-files.rst
> +Atunci când lucrăm cu fișiere o să ne întâlnim sporadic cu nevoia de a compara două fișiere între ele.
Păi am zis mai jos

2020-11-09 22:24 UTC, edi33416 commented on chapters/improve-cli/inspect-files.rst
> +Atunci când lucrăm cu fișiere o să ne întâlnim sporadic cu nevoia de a compara două fișiere între ele.
Mai vrei? :)))

2020-11-09 22:24 UTC, edi33416 commented on chapters/improve-cli/inspect-files.rst
> +#. Deoarece directorul ``~/workspace/C`` este un repository de git putem folosi utilitarul ``git`` pentru a vedea diferentețe.
m-ai lăsat fără exerciții :)))

2020-11-09 22:27 UTC, edi33416 commented on chapters/improve-cli/inspect-files.rst
> +Vom discuta mai multe despre acesta în secțiunea Înlănțuirea comenzilor.
e în următoarea secțiune din capitolul ăsta

2020-11-09 22:40 UTC, edi33416 commented on chapters/improve-cli/inspect-files.rst
> +Dacă dorim să căutăm cuvântul **search** folosim sintaxa ``\b`` (boundary) pentru a delimita patternul, ca în exemplul de mai jos:
să fie câte un fișier cu bonusuri / extrauri per secțiune?

2020-11-09 22:41 UTC, edi33416 commented on chapters/improve-cli/inspect-files.rst
> +Folosind o expresie regulată putem să căutăm după șiruri de caractere care se potrivesc cu descrierea dată în expresia regulată.
păi nu în capitolul ăsta era?

2020-11-09 22:47 UTC, edi33416 commented on chapters/improve-cli/inspect-files.rst
> +Caracterul special ``.``
Am pus, dar mă tem că mai mult îi băgăm în ceață și acum le dăm confuzia.
Adică nu știu dacă s-ar fi dus cu gândul la directorul curent fără precizarea asta :)))

2020-11-09 22:48 UTC, edi33416 commented on chapters/improve-cli/inspect-files.rst
> +Astfel, observăm cum caracterul ``.`` a înlocuit, pe rând, caracterele ``n``, ``a``, ``a`` și `` `` (space).
nu știu cum să pun space :(
help

2020-11-09 22:52 UTC, edi33416 commented on chapters/improve-cli/improve-shell.rst
> +O parte din aceste aliasuri sunt definite în fișierul ``~/.bashrc``, iar altele în fișierul ``~/.bash_aliases``.
am zis mai jos

2020-11-09 22:53 UTC, edi33416 commented on chapters/improve-cli/improve-shell.rst
> +Conținutul fișierului ``~/.bash_aliases`` este inclus de către fișierul ``~/.bashrc`` la pornirea shellului bash.
acu am văzut :))

2020-11-09 22:59 UTC, edi33416 commented on chapters/improve-cli/improve-shell.rst
> +* **STDERR** are asociat descriptorul de fișier 2
personal, mi-ar plăcea să știe că se numesc file descriptori.
Nu văd cu ce strică să știe terminologia; în plus, dacă caută pe Google, pe StackOverflow tot file descriptors o să găsească în explicații. Mă gândesc că știind și de aici n-or să se intimideze de răspunsurile ălora.
My 2cents :))

Te opui "hard"?

2020-11-09 23:01 UTC, edi33416 commented on chapters/improve-cli/improve-shell.rst
> +Folosim operatorul ``>`` pentru a redirecta **STDOUT** sau **STDERR** într-un fișier.
Am uitat să bag exemplu cu `<`.
Nici nu știu dacă are rost să bag, pt că nu cred că am folosit de 10 ori în viață..
E clasica `while ... read < input-file` pe care o caut mereu pe Google :))

2020-11-09 23:17 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/13/merge

2020-11-10 09:59 UTC, edi33416 commented on chapters/improve-cli/inspect-fs.rst
>  * Navigarea prin paginile manualului: search (/, ?, n, N), go up (g), go down (G), help (h) în timp ce folosim comanda man pt a afla mai multe despre cum o putem folosi mai bine; bonus: j/k pt naviga
m-ai rupt cu asta..

2020-11-10 13:27 UTC, edi33416 commented on chapters/improve-cli/inspect-fs.rst
> +Navigarea sistemului de fișiere: comanda ``cd``
am șters-o

2020-11-10 14:16 UTC, edi33416 commented on chapters/improve-cli/inspect-fs.rst
>  * Navigarea prin paginile manualului: search (/, ?, n, N), go up (g), go down (G), help (h) în timp ce folosim comanda man pt a afla mai multe despre cum o putem folosi mai bine; bonus: j/k pt naviga
aa, te refereai la a pune backticks. Am făcut

2020-11-10 14:19 UTC, edi33416 commented on chapters/improve-cli/improve-shell.rst
> +    -rw------- 1 student student    10992 nov  6 14:56 ./.ICEauthority
l-aș lăsa ca să fie și ceva mai extra. Am impresia că am tot prezentat lucruri foarte simple.
O să-l readuc în primplan și în capitolul următor

2020-11-10 14:54 UTC, edi33416 commented on chapters/improve-cli/improve-shell.rst
> +O astfel de înlănțuire de comenzi este numită oneliner.
explicația cu ce e oneliner mi se pare prea mult.
Nu are sens să știe distincția, dpmdv.
Distincția nu-i ajută cu nimic. Vrei să legi niște comenzi, uite cum faci.

2020-11-10 14:55 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/13/merge

2020-11-10 15:29 UTC, razvand commented on chapters/improve-cli/improve-terminal.rst
> +Un astfel de scenariu este dat de dezvoltarea aplicațiilor, scenariu pe care îl putem sparge în trei componente (sub-taskuri): scrierea aplicației, compilarea aplicației și testarea aplicației.
task

2020-11-10 15:29 UTC, razvand commented on chapters/improve-cli/improve-terminal.rst
> +Separarea logică în fereastră per task și tab per sub-task este benefică atunci când vă ocupați concomitent de mai multe lucruri.
task

2020-11-10 15:29 UTC, razvand commented on chapters/improve-cli/improve-terminal.rst
> +Puteți folosi exercițiile de la dezvoltarea aplicațiilor ca suport pentru spargerea în taskuri și sub-taskuri.
task

2020-11-10 15:29 UTC, razvand commented on chapters/improve-cli/improve-terminal.rst
> +.. image:: img/bash-history.png
de acord

2020-11-10 15:30 UTC, razvand commented on chapters/improve-cli/improve-terminal.rst
> +.. image:: img/bash-history.png
adică pus code block

2020-11-10 15:31 UTC, razvand commented on chapters/improve-cli/improve-terminal.rst
> +Pentru a naviga între instanțe ale aceleiași aplicații (ex. două terminale deschise în două ferestre diferite) putem folosi combinația de taste ``Alt+~``.
Nu e cazul. Lasă doar aici.

2020-11-10 15:31 UTC, razvand commented on chapters/improve-cli/inspect-fs.rst
> +Afișarea informațiilor extinse despre fișiere
Da, zi-le ca reminder, nu strică. Dar fă referință la capitolul scris de @CostinCarabas

2020-11-10 15:32 UTC, razvand commented on chapters/improve-cli/inspect-fs.rst
> +Navigarea sistemului de fișiere: comanda ``cd``
scoate

2020-11-10 15:32 UTC, razvand commented on chapters/improve-cli/inspect-fs.rst
> +Explorarea sistemului de fișiere: comanda ``ls``
Bine, scoate tot. Igoră ideea mea de reminder pentru fișiere ascunse. Scoate tot de file system.

2020-11-10 15:33 UTC, razvand commented on chapters/improve-cli/inspect-fs.rst
> +#. Vom începe cu prima coloană din exemplul de mai sus: ``drwxr-xr-x``.
Da, doar globbing.

2020-11-10 15:33 UTC, razvand commented on chapters/improve-cli/inspect-fs.rst
> +Sintaxa specială ``[]``
Eu aș lăsa ca o formă mai "completă". Și pune referință la globbing.

2020-11-10 15:34 UTC, razvand commented on chapters/improve-cli/inspect-fs.rst
> +Sintaxa specială ``{}``
E OK, pe scurt. Cu referință la un document / pagină / site cu globbing.

2020-11-10 15:34 UTC, razvand commented on chapters/improve-cli/inspect-files.rst
> +#. Analizați, folosind ``less``, algoritmul de căutare din fișierul ``workspace/C/searching/linear_search.c``.
Cred că se referă @CostinCarabas la separarea exercițiilor de restul laboratorului.

2020-11-10 16:04 UTC, edi33416 commented on chapters/improve-cli/improve-terminal.rst
> +.. image:: img/settings-keyboard-shortcuts.png
ăstea le fac acum

2020-11-10 16:04 UTC, edi33416 commented on chapters/improve-cli/improve-terminal.rst
> +.. image:: img/hello-multi-tabs.png
ăstea le fac acum

2020-11-10 16:05 UTC, edi33416 commented on chapters/improve-cli/inspect-fs.rst
> +Navigarea sistemului de fișiere: comanda ``cd``
am scos

2020-11-10 16:07 UTC, edi33416 commented on chapters/improve-cli/inspect-files.rst
> +#. Analizați, folosind ``less``, algoritmul de căutare din fișierul ``workspace/C/searching/linear_search.c``.
Așa este în majoritatea locurilor. Sunt și câteva inline, care sunt precedate de **Exercițiu**, dar sunt puține

2020-11-10 16:07 UTC, edi33416 commented on chapters/improve-cli/improve-shell.rst
> +Am scris, prin încercări succesive, onelinerul care ne afișează primele zece procese care consumă cea mai multă memorie.
ce a zis @lizababu

2020-11-10 16:09 UTC, edi33416 commented on chapters/improve-cli/inspect-fs.rst
> +Explorarea sistemului de fișiere: comanda ``ls``
o să șterg. O iei dintr-un commit mai vechi, sau mi-o ceri dacă nu mai apare p-aci

2020-11-10 16:10 UTC, edi33416 commented on chapters/improve-cli/inspect-fs.rst
> +Termenul vine de la cuvântul **escape** (a scăpa), și exprimă că scăpăm de semnificația specială a unui caracter / set de caractere.
Nu am mai băgat, ca să fie scurt.
Am pus la exerciții

2020-11-10 16:11 UTC, edi33416 commented on chapters/improve-cli/inspect-files.rst
> +    student@uso:~$ ps -aux --sort=%mem
actualizez acum

2020-11-10 16:11 UTC, edi33416 commented on chapters/improve-cli/inspect-files.rst
> +Compararea octet cu octet
cred că ajung să explic prea mult o chestie mică și risc să aduc mai multă confuzie

2020-11-10 17:06 UTC, razvand requested changes
Adaugă recenzie.

2020-11-10 17:06 UTC, razvand commented on chapters/improve-cli/inspect-files.rst
> +Observăm că pentru un fișier cu un număr mare de linii, așa cum este **binary_search.c**, afișarea întregului conținut pe ecran devine un impediment în a putea înțelege și urmării conținutul.
urmări

2020-11-10 17:06 UTC, razvand commented on chapters/improve-cli/inspect-files.rst
> +    student@uso:~$ ps -aux --sort=%mem
-ef, what she said

2020-11-10 17:06 UTC, razvand commented on chapters/improve-cli/inspect-files.rst
> +Așa cum am văzut până în acest punct din carte, majoritatea comenzilor linux afișează o gamă largă de informații pe care apoi utilizatorul (adică noi) le filtrează pentru a extrage ceea ce îl intrese
Linux

2020-11-10 17:06 UTC, razvand commented on chapters/improve-cli/inspect-files.rst
> +Dacă dorim să căutăm cuvântul **search** folosim sintaxa ``\b`` (boundary) pentru a delimita patternul, ca în exemplul de mai jos:
eu aș folosi -w la grep

2020-11-10 17:06 UTC, razvand commented on chapters/improve-cli/inspect-files.rst
> +Căutarea unei expresii regulate
Scoate asta și spune ca va fi prezentată partea de expresii regulate în capitolul următor: Prelucrarea datelor.

2020-11-10 17:06 UTC, razvand commented on chapters/improve-cli/inspect-files.rst
> +Folosim comanda ``diff` pentru a vedea diferențele dintre ``quick_sort.c`` și ``quick_sort_old.c``:
Ai un backtick lipsă după ``diff` care bușește afișarea.

2020-11-10 18:40 UTC, edi33416 commented on chapters/improve-cli/inspect-files.rst
> +Căutarea unei expresii regulate
Aici mi s-a rupt sufletul când am șters :))

2020-11-10 19:28 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/13/merge

2020-11-10 20:33 UTC, razvand requested changes
Adaugă recenzie pentru secțiunea legată de shell.

2020-11-10 20:33 UTC, razvand commented on chapters/improve-cli/improve-shell.rst
> +Există câte un fișier ``.bashrc`` în directorul home al fiecărui utilizator pentru a le permite utilizatorilor să își personalizeze comportamentul shellului lor bash, fără a intra în conflict cu conf
Bash

2020-11-10 20:33 UTC, razvand commented on chapters/improve-cli/improve-shell.rst
> +Atunci când un utilizator pornește un shell bash, conținutul fișierului ``~/.bashrc`` este citit și sunt aplicate configurările specifice utilizatorului.
Bash

2020-11-10 20:33 UTC, razvand commented on chapters/improve-cli/improve-shell.rst
> +Shellul *bash*, ca majoritatea programelor, vine cu un set de configurări default care poate nu sunt pe placul tuturor utilizatorilor.
Bash

implicite (*default*), care nu

2020-11-10 20:33 UTC, razvand commented on chapters/improve-cli/improve-shell.rst
> +Prin fișierul ``.bashrc`` utilizatorul poate modifica setul default a.î. să se potrivească cu stilul său: un exemplu des întâlnit este modificarea dimensiunii isoricului de comenzi.
a.î. -> astfel încât

istoricului

2020-11-10 20:33 UTC, razvand commented on chapters/improve-cli/improve-shell.rst
> +Shellul bash reține istoricul de comenzi în fișierul ``~/.bash_history`` din directorul home al fiecărui utilizator.
Bash

2020-11-10 20:33 UTC, razvand commented on chapters/improve-cli/improve-shell.rst
> +Cu alte cuvinte, atunci când executăm comanda ``ls`` în terminalul bash, defapt executăm comanda ``ls --color=auto``.
terminalul bash -> shellul Bash

defapt -> de fapt

2020-11-10 20:33 UTC, razvand commented on chapters/improve-cli/improve-shell.rst
> +Pentru a vedea toate aliasurile definite în instanța curentă de bash, folosim comanda ``alias``, ca în exemplul de mai jos:
bash -> Bash

2020-11-10 20:33 UTC, razvand commented on chapters/improve-cli/improve-shell.rst
> +Observăm că atât ``grep`` cât și ``egrep`` au câte un alias pentru opțiunea ``--color``, care în cazul acesta face highlight expresiei găsite.
face highlight -> evidenția

2020-11-10 20:33 UTC, razvand commented on chapters/improve-cli/improve-shell.rst
> +Putem observa asta folosind comanda următoare:
asta -> acest lucru, că nu suntem țărani

2020-11-10 20:33 UTC, razvand commented on chapters/improve-cli/improve-shell.rst
> +Acest lucru se întâmplă din cauză că fișierul ``~/.bashrc`` este citit atunci când pornim o instanță de bash (când deschidem un terminal).
Bash

2020-11-10 20:33 UTC, razvand commented on chapters/improve-cli/improve-shell.rst
> +Ca să recitim fișierul, și să aplicăm modificările, folosim comanda ``source`` ca în exemplul de mai jos:
, ca

2020-11-10 20:33 UTC, razvand commented on chapters/improve-cli/improve-shell.rst
> +Atunci când își încheie execuția, orice proces întoarce un cod de eroare, care este un număr:
cod de ieșire (*exit code*)

2020-11-10 20:33 UTC, razvand commented on chapters/improve-cli/improve-shell.rst
> +Pentru a vedea codul cu care și-a încheiat execuția o comandă folosim sintaxa ``$?``.
O singură propoziție din cele două.

2020-11-10 20:33 UTC, razvand commented on chapters/improve-cli/improve-shell.rst
> +Observăm că în cazul fișierului inexistet, comanda ``ls non-existent`` a întors valoarea ``2``, așa cum era specificat și în pagina de manual.
inexistent

2020-11-10 20:33 UTC, razvand commented on chapters/improve-cli/improve-shell.rst
> +#. Actualizați onelinerul anterior a.î. după dezarhivare să pornească compilarea proiectului folosind comanda ``make build``.
a.î. -> astfel încât

2020-11-10 20:33 UTC, razvand commented on chapters/improve-cli/improve-shell.rst
> +    -rw------- 1 student student    10992 nov  6 14:56 ./.ICEauthority
Drop it. E prea mult aici.

2020-11-10 20:33 UTC, razvand commented on chapters/improve-cli/improve-shell.rst
> +Folosim operatorul ``>`` pentru a redirecta **STDOUT** sau **STDERR** într-un fișier.
Nu băga, lasă doar > și 2>

2020-11-10 20:33 UTC, razvand commented on chapters/improve-cli/improve-shell.rst
> +* **STDERR** are asociat descriptorul de fișier 2
Drop it.

2020-11-10 20:33 UTC, razvand commented on chapters/improve-cli/improve-shell.rst
> +Implicit, operatoru ``>`` șterge (trunchează) conținutul fișierului destinație.
operatorul

2020-11-10 20:33 UTC, razvand commented on chapters/improve-cli/improve-shell.rst
> +Redirectarea erorilor la ieșirea standard
Taie secțiunea asta, e prea mult.

2022-09-30 13:50 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/13/merge

2022-11-07 15:43 UTC, lizababu commented on chapters/improve-cli/inspect-files.rst
> +Inspectăm conținutul fișierului ``workspace/C/searching/binary_search.c``, folosind utilitarul ``less`, ca în exemplul de mai jos:
```suggestion
Inspectăm conținutul fișierului ``workspace/C/searching/binary_search.c``, folosind utilitarul ``less``, ca în exemplul de mai jos:
```

2023-09-18 14:56 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/13/merge

2023-09-18 15:36 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/13/merge

2023-09-18 15:52 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/13/merge

2025-12-17 12:00 UTC, merged