Add Getting Familiar with Linux chapter structure
Sergiu121/uso-lab-book pull request #22
Opened 2020-09-11 07:52 UTC by lizababu

Am scris structura pentru capitolul de introducere: Acomodarea în Linux.

Prima secțiune (Pornirea și oprirea aplicațiilor) va fi luată din capitolul scris de @razvand Instalarea și utilizarea aplicațiilor.

Ultima secțiune va fi un cheatsheet - o agregare a tuturor comenzilor utile prezentate în acest capitol.

În rest am vorbit despre: aplicații, aplicația firefox (exemplul folosit de noi în carte pentru browser), aplicația terminal, workspace-uri.

2020-09-11 07:54 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/22/merge

2020-09-11 11:24 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/22/merge

2020-09-18 15:04 UTC, edi33416 approved these changes
Arată bine ce este acum.

2020-09-18 16:25 UTC, razvand reviewed
Arată foarte bine capitolul. Am lăsat câteva observații.

2020-09-18 16:25 UTC, razvand commented on chapters/basic/apps.rst
> +TODO: SS cu iconuri aplicații din bară
E un motiv pentru care nu ai luat imaginea cu totul din capitolul de aplicații?

2020-09-18 16:25 UTC, razvand commented on chapters/basic/apps.rst
> +**Exercițiu:** Porniți aplicația TODO și opriți-o în toate modurile de mai sus.
De ce nu Firefox, direct ca în capitolul de instalare de aplicații,

2020-09-18 16:25 UTC, razvand commented on chapters/basic/browser.rst
> +Pornirea și oprirea
Pune "Pornirea și oprirea browserului" că apare cam tăiat titlul fără "browserului".

2020-09-18 16:25 UTC, razvand commented on chapters/basic/browser.rst
> +Folosirea eficientă a browserului
spune "browserului web"

2020-09-18 16:25 UTC, razvand commented on chapters/basic/browser.rst
> +Butoane pentru navigație
navigare; navigație pare ceva maritim

2020-09-18 16:25 UTC, razvand commented on index.rst
> +   chapters/basic/cheatsheet.rst
Aș pune o secțiune simplă cu "Instalarea de noi aplicații" în care să folosească doar Ubuntu Software (interfața grafică) să instaleze aplicații noi: tutorial și exercițiu. Poate fi împrumatat conținut tot din capitolul "Instalarea și utilizarea aplicațiilor".

2020-09-18 16:35 UTC, lizababu commented on chapters/basic/apps.rst
> +**Exercițiu:** Porniți aplicația TODO și opriți-o în toate modurile de mai sus.
la fel ca mai sus

2020-09-18 16:46 UTC, razvand commented on chapters/basic/apps.rst
> +TODO: SS cu iconuri aplicații din bară
Got it, deci vrei o altă aplicație în afară de browser web. De exemplu Shutter sau un client Bittorrent sau Rhythmbox. Da?

2020-09-18 17:08 UTC, lizababu commented on chapters/basic/apps.rst
> +TODO: SS cu iconuri aplicații din bară
exact așa

2020-09-30 08:58 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/22/merge

2020-09-30 18:44 UTC, lizababu commented on index.rst
> +   chapters/basic/cheatsheet.rst
nu ar fi cam mult pentru primul laborator? momentan cred că e suficient să le pornească, să le oprească și să le folosească

cred că secțiunea asta se leagă mai bine de capitolul "Instalarea și utilizarea aplicațiilor", cum faci tu paralela acolo cu instalarea din CLI

2020-09-30 18:50 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/22/merge

2020-09-30 22:03 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/22/merge

2020-10-01 06:43 UTC, razvand commented on index.rst
> +   chapters/basic/cheatsheet.rst
Atunci pune referință la secțiunea de instalare și utilizare. Unii vor avea întrebarea asta. Și vrei să știi când ai un sistem pe mână ce poți face ca să ai acces la X.

2020-10-01 07:57 UTC, razvand requested changes
Adaugă feedback pentru capitolul "Acomodare în Linux".

Capitolul e bine scris, sunt câteva inconsecvențe, exprimări mai ambigue care trebuie corectate. De acolo numărul mare de comentarii.

Altfel, o problemă a capitolului este că e prea mult. Din capitolul numit "Acomodarea în Linux" a devenit capitolul "Folosirea interfeței grafice în Linux". E prea detaliat. La fiecare pas se prezintă toate modurile în care se face ceva. Nu merge asta pentru un capitol de introducere. Trebuie prezentat un mod (cel mai frecvent), eventual un hint la un al doilea mod și atât. Altfel e confuzant și prea multă informație pentru cineva care abia face primii pași. Detalierea se va face în capitolele respective: pentru GUI în capitolul de pornire de aplicatii, pentru browser în capitolul de rețelistică, pentru terminal / workspace în capitolul de interfață în linia de comandă.

Ce trebuie făcut:
* renunțat la prezentare exhaustivă a tuturor modurilor de a face ceva
* atunci când ceva a mai fost prezentat (că folosești Alt+F2), gata, nu se mai prezintă detaliat, cu screenshot; la fel la oprirea unei aplicații sau altceva
* exercițiile să fie mai simple: pornește într-un singur mod, gata, pa
* renunțat la anumite părți de conținut din zona de browser și de terminal: ad blocker nu, bookmarks nu, pornirea GUI din terminal nu, oprire forțată de aplicații în terminal nu etc.

2020-10-01 07:57 UTC, razvand commented on chapters/basic/browser.rst
> +În această subsecțiune vom învăța care sunt cele mai folosite componente ale unui browser web și cum să le folosim eficient.
"componente ale interfeței grafice a browserului web"

2020-10-01 07:57 UTC, razvand commented on chapters/basic/browser.rst
> +În general avem cel puțin 2 variante pentru a face o acțiune: *folosind butoane din interfața grafică* sau *folosind shortcuturi din tastatură echivalente clickurilor*.
două

2020-10-01 07:57 UTC, razvand commented on chapters/basic/browser.rst
> +Vom face o paralelă între cele 2 în această subsecțiune.
două

2020-10-01 07:57 UTC, razvand commented on chapters/basic/browser.rst
> +În general avem cel puțin 2 variante pentru a face o acțiune: *folosind butoane din interfața grafică* sau *folosind shortcuturi din tastatură echivalente clickurilor*.
Pune cele două variante în listă ordonată (i.e. `#. ...`).

2020-10-01 07:57 UTC, razvand commented on chapters/basic/browser.rst
> +Accesăm pagina **www.google.com**.
Dacă dorim să accesăm ..., trebuie să introducem șirul `www.google.com` în bara de adrese. Putem plasa cursorul în bara de adrese în două moduri: ...`#. ...` `#. ...`. Odată accesată bara de adrese putem introduce șirul `www.google.com`.

2020-10-01 07:57 UTC, razvand commented on chapters/basic/browser.rst
> +.. figure:: ./gifs/open-web-page.gif
Indentează.

2020-10-01 07:57 UTC, razvand commented on chapters/basic/browser.rst
> +Exerciții practice
Fără practice.

2020-10-01 07:57 UTC, razvand commented on chapters/basic/apps.rst
> +Exerciții de aprofundare
Fără "de aprofundare".

2020-10-01 07:57 UTC, razvand commented on chapters/basic/browser.rst
> +#. Accesați pagina **www.upb.curs.ro** folosind click-uri.
clickuri

2020-10-01 07:57 UTC, razvand commented on chapters/basic/browser.rst
> +#. Accesați pagina **www.upb.curs.ro** folosind click-uri.
curs.upb.ro

2020-10-01 07:57 UTC, razvand commented on chapters/basic/browser.rst
> +Spre exemplu, navigam pe o rețea de socializare, am deschis un articol apărut în feed, l-am citit și acum vrem să revenim la feedul de pe rețeaua de socializare.
navigăm

2020-10-01 07:57 UTC, razvand commented on chapters/basic/browser.rst
> +Putem naviga la pagini navigate anterior în 2 moduri:
două

2020-10-01 07:57 UTC, razvand commented on chapters/basic/browser.rst
> +* Folosind butoanele **săgeată stânga** (*Go back one page*) și **săgeată dreapta** (*Go forward one page*) ca în imaginea de mai jos:
butoanele ..... din interfața grafică a browserului ...

2020-10-01 07:57 UTC, razvand commented on chapters/basic/browser.rst
> +.. figure:: ./gifs/back-forward-web-pages.gif
Indentează.

2020-10-01 07:57 UTC, razvand commented on chapters/basic/browser.rst
> +    * Navigare înapoi: ``Alt+săgeată stânga`` sau ``Ctrl+[``.
E nevoie de indentare cu patru spații aici? Nu ajung două?

2020-10-01 07:57 UTC, razvand commented on chapters/basic/browser.rst
> +Exerciții practice
Fără "practice"

2020-10-01 07:57 UTC, razvand commented on chapters/basic/browser.rst
> +Accesăm pagina **https://www.hotnews.ro**.
E prima oară când apare `https://`. Aș scoate, pentru consecvență.

2020-10-01 07:57 UTC, razvand commented on chapters/basic/browser.rst
> +* Folosind touchpad-ul.
touchpadul

2020-10-01 07:57 UTC, razvand commented on chapters/basic/browser.rst
> +* Folosind combinația de taste ``Alt+scroll up`` și ``Alt+scroll down``.
Ce înseamnă `scroll up` și `scroll down`?

2020-10-01 07:57 UTC, razvand commented on chapters/basic/browser.rst
> +Putem împrospăta pagina web în mai multe moduri:
reîmprospăta

2020-10-01 07:57 UTC, razvand commented on chapters/basic/browser.rst
> +.. figure:: ./gifs/firefox-refresh.gif
Indentare

2020-10-01 07:57 UTC, razvand commented on chapters/basic/browser.rst
> +* Folosind shortcutul (*scurtătura*, *combinația de taste*) ``Ctrl+r``.
Folosind combinația de taste `Ctrl+r`. (pentru consecvență cu modul în care ai formulat mai sus).

2020-10-01 07:57 UTC, razvand commented on chapters/basic/browser.rst
> +În sub-subsecțiunile următoare vom învăța cum să deschidem, sa navigăm printre taburi și să închidem taburi eficient.
Fără "vom învăța".

2020-10-01 07:57 UTC, razvand commented on chapters/basic/browser.rst
> +Atunci când deschide aplicația Firefox se deschide într-un tab, pe pagina principală.
You accidentally the verb.

2020-10-01 07:57 UTC, razvand commented on chapters/basic/browser.rst
> +.. figure:: ./gifs/firefox-open-tabs.gif
Indentează.

2020-10-01 07:57 UTC, razvand commented on chapters/basic/browser.rst
> +* Folosind scurtătura (*shortcutul*, *combinația de taste*) ``Ctrl+t``.
combinația de taste (damn, girl, consecvența nu e punctul tău forte)

2020-10-01 07:57 UTC, razvand commented on chapters/basic/browser.rst
> +**Exerciții practice**
fără "practice"

2020-10-01 07:57 UTC, razvand commented on chapters/basic/browser.rst
> +Putem deschide un alt tab în browser în mai multe moduri:
două moduei

2020-10-01 07:57 UTC, razvand commented on chapters/basic/browser.rst
> +* Folosind butonul cu simbolul ``+`` din browser:
din interfața grafică a browserului

2020-10-01 07:57 UTC, razvand commented on chapters/basic/browser.rst
> +#. Deschideți 2 taburi noi folosind simbolul ``+``.
două

2020-10-01 07:57 UTC, razvand commented on chapters/basic/browser.rst
> +#. Deschideți 2 taburi noi folosind simbolul ``+``.
Nu pune listă ordonată. E un singur exercițiu.

2020-10-01 07:57 UTC, razvand commented on chapters/basic/browser.rst
> +Avem acum 3 taburi deschise:
trei

2020-10-01 07:57 UTC, razvand commented on chapters/basic/browser.rst
> +#. În primul tab deschis navigați pe pagina **www.ubuntu.com**, iar în al doilea pe pagina **www.google.com/gmail/**. Folosiți shortcutul ``Ctrl+l`` și apoi scrieți adresa paginilor.
Aș folosi în loc de gmail o pagină care nu are nevoie de autentificare pentru a afișa o informație utilă. Poate wikipedia, poate ocw.

2020-10-01 07:57 UTC, razvand commented on chapters/basic/browser.rst
> +.. figure:: ./gifs/firefox-navigate-tabs.gif
Indentează

2020-10-01 07:57 UTC, razvand commented on chapters/basic/browser.rst
> +* Folosind shortcutul (*scurtătura*, *combinația de taste*) ``Alt+număr``.
`<număr>`.

2020-10-01 07:57 UTC, razvand commented on chapters/basic/browser.rst
> +* Folosind shortcutul (*scurtătura*, *combinația de taste*) ``Alt+număr``.
combinația de taste

2020-10-01 07:57 UTC, razvand commented on chapters/basic/browser.rst
> +**Exerciții practice**
Fără "practice"

2020-10-01 07:57 UTC, razvand commented on chapters/basic/browser.rst
> +#. Deschideți încă 2 taburi pe lângă cele 3 deja deschise.
două, trei

2020-10-01 07:57 UTC, razvand commented on chapters/basic/browser.rst
> +Atunci când nu mai avem nevoie să avem o pagină deschisă este bine să închidem tabul.
Nu e nevoie de fraza asta. Ajunge următoarea.

2020-10-01 07:57 UTC, razvand commented on chapters/basic/browser.rst
> +.. figure:: ./gifs/firefox-close-tabs.gif
Indentează

2020-10-01 07:57 UTC, razvand commented on chapters/basic/browser.rst
> +**Exerciții practice**
fără "practice"

2020-10-01 07:57 UTC, razvand commented on chapters/basic/browser.rst
> +Vrem să găsim rețeta perfectă pentru supă de pui gătită în casă și vrem să deschidem mai multe rețete, fiecare într-un tab, pentru a le compara și a alege rețeta cea mai bună.
Să presupunem că ...

2020-10-01 07:57 UTC, razvand commented on chapters/basic/browser.rst
> +Vom învăța cum să deschide linkurile de rețete găsite pe Google într-un alt tab.
Fără "vom învăța".

2020-10-01 07:57 UTC, razvand commented on chapters/basic/browser.rst
> +Vom învăța cum să deschide linkurile de rețete găsite pe Google într-un alt tab.
Argumentează care sunt alternativele și de ce modul ăsta este (evident) mai eficient.

2020-10-01 07:57 UTC, razvand commented on chapters/basic/browser.rst
> +.. figure:: ./gifs/firefox-search-for-chicken-soup.gif
Indentează.

2020-10-01 07:57 UTC, razvand commented on chapters/basic/browser.rst
> +Putem deschide rețele găsite în alte taburi în mai multe moduri:
rețete

2020-10-01 07:57 UTC, razvand commented on chapters/basic/browser.rst
> +* Folosind clickuri. Folosim *click dreapta* pe link după care apăsăm *Open Link in New Tab* ca în imaginea de mai jos:
după care alegem opțiunea *Open Link in New Tab* din meniul contextual ca în imaginea de mai jos:

2020-10-01 07:57 UTC, razvand commented on chapters/basic/browser.rst
> +.. figure:: ./gifs/firefox-open-link-in-tab.gif
Indentează

2020-10-01 07:57 UTC, razvand commented on chapters/basic/browser.rst
> +**Exerciții practice**
Fără "practice".

2020-10-01 07:57 UTC, razvand commented on chapters/basic/browser.rst
> +#. Navigați printre paginile deschise folosind combinația de taste ``Alt+număr``.
`Alt+<număr>`

2020-10-01 07:57 UTC, razvand commented on chapters/basic/browser.rst
> +Folosirea bookmark-urilor
bookmarkurilor

2020-10-01 07:57 UTC, razvand commented on chapters/basic/browser.rst
> +Ca să nu pierdem aceste pagini folosim **Bookmarkuri**.
virgulă înainte de "folosim"

2020-10-01 07:57 UTC, razvand commented on chapters/basic/browser.rst
> +.. figure:: ./gifs/firefox-bookmark-page-long.gif
Indentează tot până la următorul element din lista neordonată, inclusiv lista ordonată de mai jos.

2020-10-01 07:57 UTC, razvand commented on chapters/basic/browser.rst
> +* Folosind combinația de taste (*scurtătura*, *shortcutul*) ``Ctrl+d`` și apăsarea butonului *Done* ca în modurile de mai sus.
fără (*scurtătura*, *shortcutul*) (pentru consecvență).

2020-10-01 07:57 UTC, razvand commented on chapters/basic/browser.rst
> +Putem vizualiza toate bookmark-urile pe care le-am create în mai multe moduri:
bookmarkurile

creat

2020-10-01 07:57 UTC, razvand commented on chapters/basic/browser.rst
> +.. figure:: ./gifs/firefox-view-bookmarks.gif
Indentează.

2020-10-01 07:57 UTC, razvand commented on chapters/basic/browser.rst
> +Exerciții practice
Fără "practice"

2020-10-01 07:57 UTC, razvand commented on chapters/basic/browser.rst
> +Instalarea şi folosirea unui ad blocker
Mi se pare cam mult asta aici.

2020-10-01 07:57 UTC, razvand commented on chapters/basic/browser.rst
> +Instalarea şi folosirea unui ad blocker
ș nu este comma below

2020-10-01 07:57 UTC, razvand commented on chapters/basic/browser.rst
> +În această sub-subsecțiune vom instala ad blocker-ul `AdBlock Plus <https://adblockplus.org>`_ care vine sub forma unui **plug-in** (*o extensie*) pentru browerul web care elimină (pe cât posibil) re
Încheie fraza după "pentru browserul web". Apoi vine o propoziție nouă.

2020-10-01 07:57 UTC, razvand commented on chapters/basic/browser.rst
> +În această sub-subsecțiune vom instala ad blocker-ul `AdBlock Plus <https://adblockplus.org>`_ care vine sub forma unui **plug-in** (*o extensie*) pentru browerul web care elimină (pe cât posibil) re
ad blockerul

2020-10-01 07:57 UTC, razvand commented on chapters/basic/browser.rst
> +Pașii instalării unui ad blocker
Nu e nevoie de o sub-subsecțiune. Spune direct: "Așa cum apare și în imaginea de mai sus, pașii de instalarea unui ad blocker sun:".

2020-10-01 07:57 UTC, razvand commented on chapters/basic/terminal.rst
> +**Gnome Terminal** (uzual folosit *terminalul*) este o aplicație software, la fel ca *LibreOffice* și *Firefox*.
GNO<E

2020-10-01 07:57 UTC, razvand commented on chapters/basic/terminal.rst
> +Terminalul este folosit în general pentru rularea **aplicații software** (*programe*, *utilitare*) care nu au **interfață grafică** (*GUI*).
, în general,

2020-10-01 07:57 UTC, razvand commented on chapters/basic/terminal.rst
> +Folosim linia de comandă prin intermediul aplicației *Gnome Terminal* care are identificatorul **gnome-terminal**.
GNOME

2020-10-01 07:57 UTC, razvand commented on chapters/basic/terminal.rst
> +Fiind o aplicație ca oricare alta, avem mai multe moduri prin care putem să **deschidem** aplicația *Gnome Terminal*:
Din nou, referință la secțiunea anterioară în care ai prezentat pornirea aplicațiilor.

2020-10-01 07:57 UTC, razvand commented on chapters/basic/terminal.rst
> +.. figure:: ./gifs/open-terminal-icon.gif
Indentează.

2020-10-01 07:57 UTC, razvand commented on chapters/basic/terminal.rst
> +.. figure:: ./gifs/open-terminal-alt-f2.gif
Indentează.

2020-10-01 07:57 UTC, razvand commented on chapters/basic/terminal.rst
> +.. figure:: ./gifs/open-terminal-right-click.gif
Indentează.

2020-10-01 07:57 UTC, razvand commented on chapters/basic/terminal.rst
> +.. figure:: ./gifs/close-terminal-x.gif
Indentează.

2020-10-01 07:57 UTC, razvand commented on chapters/basic/terminal.rst
> +    :alt: Închiderea aplicației *Gnome Terminal* folosind butonul ``x``
GNOME

2020-10-01 07:57 UTC, razvand commented on chapters/basic/terminal.rst
> +* Folosind combinația de taste ``Shift+Ctrl+q``.
`Ctrl+Shift+q`

2020-10-01 07:57 UTC, razvand commented on chapters/basic/terminal.rst
> +
Nu ai zis de `Ctrl+d`.

2020-10-01 07:57 UTC, razvand commented on chapters/basic/terminal.rst
> +#. Deschideți aplicația *Gnome Terminal* în toate modurile de mai sus (veți avea aplicația *Gnome Terminal* deschisă de 4 ori).
patru

2020-10-01 07:57 UTC, razvand commented on chapters/basic/terminal.rst
> +Exerciții practice
Fără "practice"

2020-10-01 07:57 UTC, razvand commented on chapters/basic/terminal.rst
> +#. Deschideți aplicația *Gnome Terminal* în toate modurile de mai sus (veți avea aplicația *Gnome Terminal* deschisă de 4 ori).
GNOME

2020-10-01 07:57 UTC, razvand commented on chapters/basic/terminal.rst
> +Ca să facem acest lucru putem să deschidem 2 terminale: unul cu aplicația pe care vrem să o monitorizăm și unul în care pornim aplicația de monitorizare.
două

2020-10-01 07:57 UTC, razvand commented on chapters/basic/terminal.rst
> +În următoarele sub-subsecțiuni vom vorbi despre cum să deschidem, să închidem și să navigăm printe taburile din terminal.
printre

2020-10-01 07:57 UTC, razvand commented on chapters/basic/terminal.rst
> +Deschide din nou aplicația *Gnome Terminal*.
Deschideți

2020-10-01 07:57 UTC, razvand commented on chapters/basic/terminal.rst
> +Deschide din nou aplicația *Gnome Terminal*.
GNOME

2020-10-01 07:57 UTC, razvand commented on chapters/basic/terminal.rst
> +.. figure:: ./gifs/terminal-open-tabs-menu.gif
Indentează.

2020-10-01 07:57 UTC, razvand commented on chapters/basic/terminal.rst
> +Apăsăm pe butonul *File* după care pe butonul *New Tab*.
Nu e buton. E opțiune într-un meniu.

2020-10-01 07:57 UTC, razvand commented on chapters/basic/terminal.rst
> +    :alt: Deschiderea taburilor în terimal folosind click dreapta
terminal

2020-10-01 07:57 UTC, razvand commented on chapters/basic/terminal.rst
> +* Folosind shortcutul (*combinația de taste*) ``Ctrl+Shift+t``.
combinația de taste

2020-10-01 07:57 UTC, razvand commented on chapters/basic/terminal.rst
> +.. figure:: ./gifs/terminal-close-tabs-x.gif
Indentează

2020-10-01 07:57 UTC, razvand commented on chapters/basic/terminal.rst
> +.. figure:: ./gifs/terminal-close-tabs-menu.gif
Indentează

2020-10-01 07:57 UTC, razvand commented on chapters/basic/terminal.rst
> +Exerciții practice
Fără "practice".

2020-10-01 07:57 UTC, razvand commented on chapters/basic/terminal.rst
> +#. Deschideți 2 taburi de terminal noi folosind combinația de taste ``Ctrl+Shift+t``,
două

2020-10-01 07:57 UTC, razvand commented on chapters/basic/terminal.rst
> +.. figure:: ./gifs/terminal-navigate-tabs.gif
Indentează.

2020-10-01 07:57 UTC, razvand commented on chapters/basic/terminal.rst
> +* Folosind combinația de taste ``Alt+număr`` unde *număr* este numărul (*indexul*) tabului la care vrem să ajungem.
`<număr>`

2020-10-01 07:57 UTC, razvand commented on chapters/basic/terminal.rst
> +Exerciții practice
Fără "practice"

2020-10-01 07:57 UTC, razvand commented on chapters/basic/terminal.rst
> +În sub-subsecțiunile următoare vom vorbi despre scrollul, copierea și lipirea textului în terminal și despre golirea ecranului de termninal.
terminal

2020-10-01 07:57 UTC, razvand commented on chapters/basic/terminal.rst
> +Vrem să evităm greșile de scriere pe cât posibil.
tastare (nu scriere)

2020-10-01 07:57 UTC, razvand commented on chapters/basic/terminal.rst
> +Folosirea acestor feature-uri este un mod de a preveni greșeli de scriere.
tastare

2020-10-01 07:57 UTC, razvand commented on chapters/basic/terminal.rst
> +Pentru reîmprospătarea ecranului de termninal avem mai multe variante:
golirea

2020-10-01 07:57 UTC, razvand commented on chapters/basic/terminal.rst
> +.. figure:: ./gifs/terminal-clear.gif
Indentează.

2020-10-01 07:57 UTC, razvand commented on chapters/basic/terminal.rst
> +În Ubuntu 20.04, copiem text în mai multe moduri:
18.04

2020-10-01 07:57 UTC, razvand commented on chapters/basic/terminal.rst
> +.. figure:: ./gifs/ubuntu-copy-text.gif
Indentează.

2020-10-01 07:57 UTC, razvand commented on chapters/basic/terminal.rst
> +* Selectăm textul și apăsăm combinația de taste ``Ctrl+c``.
NU. NU mai zice asta că încurci lumea. Asta e ceva distinct, nu se leagă de terminal. Nu o pune aici că e confusing.

2020-10-01 07:57 UTC, razvand commented on chapters/basic/terminal.rst
> +În cadrul aplicației *Gnome Terminal* copierea textului se face diferit față de alte aplicații, în mai multe moduri:
GNOME

2020-10-01 07:57 UTC, razvand commented on chapters/basic/terminal.rst
> +.. figure:: ./gifs/terminal-copy.gif
Indentează

2020-10-01 07:57 UTC, razvand commented on chapters/basic/terminal.rst
> +* Selectăm textul și apăsăm combinația de taste ``Ctrl+Shift+c``.
Sau `Ctrl+Insert` (eu asta folosesc).

2020-10-01 07:57 UTC, razvand commented on chapters/basic/terminal.rst
> +În Ubuntu 20.04, lipim text în mai multe moduri:
18.04

2020-10-01 07:57 UTC, razvand commented on chapters/basic/terminal.rst
> +În cadrul aplicației *Gnome Terminal* lipirea textului se face diferit față de alte aplicații, în mai multe moduri:
GNOME

2020-10-01 07:57 UTC, razvand commented on chapters/basic/terminal.rst
> +* Apăsăm *click dreapta* și apăsăm butonul *Paste* ca în imaginea de mai jos:
De renunțat la partea asta "generică", așa cum am zis mai sus.

2020-10-01 07:57 UTC, razvand commented on chapters/basic/terminal.rst
> +Pornirea aplicațiilor grafice din terminal
Asta nu are sens aici, nu? Parcă a fost prezentată în zona de pornire a aplicațiilor.

2020-10-01 07:57 UTC, razvand commented on chapters/basic/terminal.rst
> +Pornim o aplicație de terminal folosind fie iconul corespunzător fie Alt+F2 urmat de șirul (comanda) gnome-terminal.
monotype pentru Alt+F2 și gnome-terminal

2020-10-01 07:57 UTC, razvand commented on chapters/basic/terminal.rst
> +Exerciții practice
fără "practice"

2020-10-01 07:57 UTC, razvand commented on chapters/basic/terminal.rst
> +Exerciții practice
Drop this section.

2020-10-01 07:57 UTC, razvand commented on chapters/basic/terminal.rst
> +Exerciții practice
Fără "practice".

2020-10-01 07:57 UTC, razvand commented on chapters/basic/terminal.rst
> +Exerciții practice
Fără "practice"

2020-10-01 08:00 UTC, lizababu commented on chapters/basic/browser.rst
> +Acesta este browserul default instalat în Ubuntu 20.04.
a schimbat Andrei Martin ieri mașina virutală; a trecut de la 18.04 la 20.04; trecem și noi la carte la asta, nu?

2020-10-01 08:18 UTC, lizababu commented on chapters/basic/browser.rst
> +Instalarea şi folosirea unui ad blocker
mamă am dat copy paste de la Sergiu, nu m-am mai gândit, uitasem că el are probleme

2020-10-01 13:30 UTC, lizababu commented on chapters/basic/browser.rst
> +#. Accesați pagina **www.upb.curs.ro** folosind click-uri.
m-am gândit că e suficient de mult 2 cu 2

2020-10-01 13:31 UTC, lizababu commented on chapters/basic/browser.rst
> +    * Navigare înapoi: ``Alt+săgeată stânga`` sau ``Ctrl+[``.
așa e TAB-ul în tot fișierul (1 TAB = 4 spaces)

2020-10-01 13:32 UTC, lizababu commented on chapters/basic/browser.rst
> +Accesăm pagina **https://www.hotnews.ro**.
da, mi-a scăpat, am scos

2020-10-01 13:34 UTC, lizababu commented on chapters/basic/browser.rst
> +* Folosind combinația de taste ``Alt+scroll up`` și ``Alt+scroll down``.
să-ți spun drept, am luat asta de pe goagle http://7is7.com/software/firefox/shortcuts.html pentru că eu n-am tastatură cu num keys (nici nu știu cum se numește) și nu folosesc page up, page up toate alea

cred că se referă la Page Up și Page Down, verifici tu te rog?

2020-10-01 13:46 UTC, lizababu commented on chapters/basic/browser.rst
> +#. Deschideți 2 taburi noi folosind simbolul ``+``.
eu voiam să fie 2: unul deschidere de taburi, altul Ctrl+l

2020-10-01 13:47 UTC, lizababu commented on chapters/basic/browser.rst
> +#. În primul tab deschis navigați pe pagina **www.ubuntu.com**, iar în al doilea pe pagina **www.google.com/gmail/**. Folosiți shortcutul ``Ctrl+l`` și apoi scrieți adresa paginilor.
adică să refac GIF-urile? :(

2020-10-01 13:53 UTC, lizababu commented on chapters/basic/browser.rst
> +Instalarea şi folosirea unui ad blocker
îi dau lui Serigu s-o integreze la el dacă vrea

2020-10-01 14:03 UTC, lizababu commented on chapters/basic/terminal.rst
> +    :alt: Deschiderea taburilor în terimal folosind click dreapta
=)))))

2020-10-01 14:13 UTC, lizababu commented on chapters/basic/terminal.rst
> +Pornirea aplicațiilor grafice din terminal
la pornirea aplicațiilor m-am limitat la a le porni doar din clickuri, nu din terminal

2020-10-01 14:14 UTC, lizababu commented on chapters/basic/terminal.rst
> +Pornirea aplicațiilor grafice din terminal
adică din ce aveai tu scris, eu am luat doar partea cu deschiderea din GUI

2020-10-01 14:23 UTC, lizababu commented on chapters/basic/browser.rst
> +Atunci când deschide aplicația Firefox se deschide într-un tab, pe pagina principală.
=))))

2020-10-01 14:34 UTC, razvand commented on chapters/basic/browser.rst
> +#. În primul tab deschis navigați pe pagina **www.ubuntu.com**, iar în al doilea pe pagina **www.google.com/gmail/**. Folosiți shortcutul ``Ctrl+l`` și apoi scrieți adresa paginilor.
Lasă-l așa atunci :-)

2020-10-01 14:34 UTC, razvand commented on chapters/basic/terminal.rst
> +Pornirea aplicațiilor grafice din terminal
Mi se pare că e prea mult pentru acest capitol de acomodare.

2020-10-01 14:48 UTC, lizababu commented on chapters/basic/terminal.rst
> +Pornirea aplicațiilor grafice din terminal
am tăiat-o; keeping it simple

2020-10-01 15:04 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/22/merge

2020-10-01 15:38 UTC, razvand commented on chapters/basic/browser.rst
> +#. Accesați pagina **www.upb.curs.ro** folosind click-uri.
Mi se pare că asta complică enunțul.

2020-10-01 16:38 UTC, razvand commented on chapters/basic/browser.rst
> +#. Deschideți 2 taburi noi folosind simbolul ``+``.
OK, Pune 2 atunci.

2020-10-02 11:09 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/22/merge

2020-10-02 11:19 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/22/merge

2020-10-02 11:21 UTC, lizababu commented on chapters/basic/browser.rst
> +#. În primul tab deschis navigați pe pagina **www.ubuntu.com**, iar în al doilea pe pagina **www.google.com/gmail/**. Folosiți shortcutul ``Ctrl+l`` și apoi scrieți adresa paginilor.
mă sperii :)

2020-10-02 11:31 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/22/merge

2020-10-02 11:40 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/22/merge

2020-10-05 20:19 UTC, razvand requested changes
Foarte bun capitolul. Secțiunea de cheatsheet e gaura la macaroană.

Am comentat mai mult chestiuni de formă. După ce le rezolvi, totul e OK cu mine.

2020-10-05 20:19 UTC, razvand commented on chapters/basic/browser.rst
> +* Folosind linia de comandă ca în imaginea de mai jos:
Spune că deschidem un terminal și tasăm în terminal comanda de pornire (aici `firefox`), similar cu folosirea Alt+F2.

2020-10-05 20:19 UTC, razvand commented on chapters/basic/browser.rst
> +Putem opri browserul Firefox în mai multe moduri:
Fă referință la secțiunea anterioară.

2020-10-05 20:19 UTC, razvand commented on chapters/basic/browser.rst
> +#. Folosind combinația de taste din tastatură echivalente clickurilor
Argumentează că folosirea combinației de taste este mai rapidă, mai eficientă, dar necesită un efort de memorare din partea utilizatorului. Utilizatori avansați vor folosi preponderent combinații de taste.

2020-10-05 20:19 UTC, razvand commented on chapters/basic/browser.rst
> +**Exercițiu:** Accesați paginile **www.curs.upb.ro**, **www.studenti.pub.ro**, **www.hotnews.ro**, **www.facebook.com** folosind ambele metode prezentate mai sus.
Nu le mai pune cu www în față, că nu mai face nimeni asta. Direct fără www.

2020-10-05 20:19 UTC, razvand commented on chapters/basic/browser.rst
> +  * Navigare înainte: ``Alt+săgeată dreapta```.
Ai un backtick în plus.

2020-10-05 20:19 UTC, razvand commented on chapters/basic/browser.rst
> +#. Deschideți pagina **www.youtube.com**.
Nu e cronologică formularea. Spune "Folosind combinația de taste ``Ctlr+l``, accesați bara de adrese a browserului și deschideți pagina **youtube.com**." Lasă moartea www-ul ăla din față.

2020-10-05 20:19 UTC, razvand commented on chapters/basic/browser.rst
> +#. În primul tab deschis navigați pe pagina **www.ubuntu.com**, iar în al doilea pe pagina **www.google.com/gmail/**. Folosiți combinația de taste ``Ctrl+l`` și apoi scrieți adresa paginilor.
fără www-uri. gmail nu e ceva util fără autentificare, recomand altă pagină.

2020-10-05 20:19 UTC, razvand commented on chapters/basic/browser.rst
> +Navigarea printre taburi
Între nu printre, că nu faci slalom.

2020-10-05 20:19 UTC, razvand commented on chapters/basic/browser.rst
> +#. Al treilea pe pagina **www.google.com/gmail/**.
nu gmail

2020-10-05 20:19 UTC, razvand commented on chapters/basic/terminal.rst
> +Vom aprofunda aceste lucruri în capitolul TODO.
Referință la capitolul lui Edi.

2020-10-05 20:19 UTC, razvand commented on chapters/basic/terminal.rst
> +Deschideți din nou aplicația *GNOME Terminal*.
Marchează cumva această frază, să fie făcută, eventual pe un rând nou. Altfel sari peste ea și nu e clar că trebuie să faci ceva. Poate mutată la secțiunea de mai jos ca prima propoziție din secțiune.

2020-10-05 20:19 UTC, razvand commented on chapters/basic/terminal.rst
> +Navigarea printe taburi
între

2020-10-05 20:19 UTC, razvand commented on chapters/basic/terminal.rst
> +* Folosind combinația de taste ``Ctrl+Shift+w``.
Nimeni nu foloseste asta. Tot Ctrl+d este comanda folosită.

2020-10-05 20:19 UTC, razvand commented on chapters/basic/terminal.rst
> +#. Închideți taburile folosind combinația de taste ``Ctrl+Shift+w``.
Ctrl+d

2020-10-05 20:19 UTC, razvand commented on chapters/basic/terminal.rst
> +Navigarea printe taburi
Leagă-te de taburile de la browser și spune că sunt combinații de taste similare.

2020-10-05 20:19 UTC, razvand commented on chapters/basic/terminal.rst
> +* Selectăm textul și apăsăm combinația de taste ``Ctrl+Shift+c``.
Revin cu precizarea că nu am folosit ever `Ctrl+Shift+c`, doar `Ctrl+Insert` + `Shift+Insert`. Aș recomanda înlocuirea cu astea, dar vezi ce folosesc și alții, poate sunt eu mai diferit.

2020-10-05 20:19 UTC, razvand commented on chapters/basic/terminal.rst
> +.. [#ctrlc]
Nu le zice de asta, e prea mult aici.

2020-10-05 20:19 UTC, razvand commented on chapters/basic/terminal.rst
> +    În terminal, combinația de taste ``Ctrl+c`` are rolul de a opri o aplicație / un utilitar pornit [#ctrlc]_.
Nu pune footnote ctrlc, e prea mult aici.

2020-10-05 20:19 UTC, razvand commented on chapters/basic/workspace.rst
> +* Folosind combinația de taste ``Alt+TAB`` ca în imaginea de mai jos:
s/TAB/Tab

2020-10-05 20:19 UTC, razvand commented on chapters/basic/cheatsheet.rst
> +.. _basic_cheatsheet:
Splendidă secțiunea asta. E ce trebuie: sumar, imagini animate, scurt și la obiect. E model pentru secțiuni de sumarizare / cheatsheet.

2020-10-05 20:43 UTC, lizababu commented on chapters/basic/cheatsheet.rst
> +.. _basic_cheatsheet:
spread the love

2020-10-05 20:44 UTC, lizababu commented on chapters/basic/terminal.rst
> +* Selectăm textul și apăsăm combinația de taste ``Ctrl+Shift+c``.
haolo, bine

2020-10-05 20:44 UTC, lizababu commented on chapters/basic/terminal.rst
> +* Selectăm textul și apăsăm combinația de taste ``Ctrl+Shift+c``.
eu spre exemplu nu folosesc Shift+Insert pentru că nu am Insert pe tastatură, de-aia am ales Ctrl+Shift+c

2020-10-05 20:55 UTC, razvand commented on chapters/basic/terminal.rst
> +* Selectăm textul și apăsăm combinația de taste ``Ctrl+Shift+c``.
Vezi ce zic și alții. Vezi @edi33416 , @Sergiu121

2020-10-05 21:57 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/22/merge

2020-10-05 22:04 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/22/merge

2020-10-05 22:05 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/22/merge

2020-10-06 07:37 UTC, CostinCarabas approved these changes

2020-10-06 14:58 UTC, edi33416 requested changes
GG, @lizababu! Ai făcut o treabă super tare!

Am găstit 3 typos. Fix și merge

2020-10-06 14:58 UTC, edi33416 commented on chapters/basic/terminal.rst
> +Terminalul este folosi, în general, pentru rularea **aplicațiilor software** (*programe*, *utilitare*) care nu au **interfață grafică** (*GUI*).
s/folosi/folosit/g

2020-10-06 14:58 UTC, edi33416 commented on chapters/basic/workspace.rst
> +Când avem prea multe aplicații deschide simultan, navigarea printre ele devine dificilă și consumatoare de timp.
s/deschide/deschise/g

2020-10-06 14:58 UTC, edi33416 commented on chapters/basic/workspace.rst
> +Creăm un workspace-urile descrise mai sus ca în imaginea de mai jos:
s/Creăm un/Creăm/g

2020-10-06 15:01 UTC, lizababu commented on chapters/basic/apps.rst
> +Vorbim despre pornirea aplicațiilor din terminal în capitolul ``Instalarea și utilizarea aplicațiilor``.
am pus momentan  în capitolul ``Instalarea și utilizarea aplicațiilor`` că nu pot să pun ref pe bune că nu știe la build de el (că nu am conținutul de la capitol + labelurile alea)

2020-10-06 15:07 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/22/merge

2020-10-06 15:34 UTC, edi33416 commented on chapters/basic/apps.rst
> +Vorbim despre pornirea aplicațiilor din terminal în capitolul ``Instalarea și utilizarea aplicațiilor``.
Am înțeles. Lasă așa atunci.

2020-10-06 15:35 UTC, edi33416 approved these changes

2020-10-06 16:55 UTC, razvand approved these changes
Recenzii de formă. Le parcurgi, aplici și apoi dai merge.

2020-10-06 16:55 UTC, razvand commented on chapters/basic/apps.rst
> +De exemplu, pornește un browser web pentru a accesa Wikipedia sau pornește aplicația Spotify pentru a asculta muzică.
, sau

2020-10-06 16:55 UTC, razvand commented on chapters/basic/apps.rst
> +De exemplu sistemul pornește un client DHCP pentru a obține automat parametrii de rețea care asigură conexiunea la Internet; sau pornește o aplicație care sincronizează data sistemului cu data indica
De exemplu,

2020-10-06 16:55 UTC, razvand commented on chapters/basic/apps.rst
> +În cazul interfeței grafice pornirea se face folosind elementele grafice (mouse, meniuri, iconuri de desktop).
În cazul intefeței grafice,

2020-10-06 16:55 UTC, razvand commented on chapters/basic/apps.rst
> +În cazul interfeței în linia de comandă pornirea se face introducând și rulând comenzi.
În cazul interfeței în linia de comandă,

2020-10-06 16:55 UTC, razvand commented on chapters/basic/apps.rst
> +De exemplu, în Ubuntu 18.04, pentru a porni aplicația Rhythmbox folosim iconul din bara de jos în stânga, la fel ca în imaginea de mai jos:
Rhythmbox,

2020-10-06 16:55 UTC, razvand commented on chapters/basic/apps.rst
> +Când apăsăm ``Alt+F2`` mediul grafic prezintă un prompt în care introducem șirul care identifică aplicația.
, mediul grafic

2020-10-06 16:55 UTC, razvand commented on chapters/basic/apps.rst
> +De exemplu, pentru a porni aplicația Rhythmbox introducem șirul ``rhythmbox`` în prompt, ca în figura de mai jos:
Rhythmbox,

2020-10-06 16:55 UTC, razvand commented on chapters/basic/apps.rst
> +    În Windows pornim un prompt de tip *application launcher* folosind combinația de taste ``Windows+r``.
În Windows,

2020-10-06 16:55 UTC, razvand commented on chapters/basic/browser.rst
> +În viața de zi cu zi aplicația pe care o folosim probabil cel mai des, indiferent de platformă sau sistem de operare, este **browserul web**.
În viața de zi cu zi,

2020-10-06 16:55 UTC, razvand commented on chapters/basic/browser.rst
> +Acesta rulează pe smartphone-uri, laptopuri, tablete și este folosit pentru rularea aplicațiilor web cum ar fi clienți de mesagerie, rularea de jocuri, afișarea de conținut al unei pagini cu știri, s
sau de continut pe rețele de socializare.

2020-10-06 16:55 UTC, razvand commented on chapters/basic/apps.rst
> +  Această combinație de taste depinde de aplicație, spre deosebire combinației de taste ``Alt+F4`` care se aplică tuturor aplicațiilor grafice.
, care se aplică.

2020-10-06 16:55 UTC, razvand commented on chapters/basic/browser.rst
> +**Browserul web** este o aplicație pe care o folosim în mod constant și ne dorim să o folosim într-un mod cât mai eficient.
; de aceea ne dorim să o folosim cât mai eficient.

2020-10-06 16:55 UTC, razvand commented on chapters/basic/browser.rst
> +Atunci când browserul este pornit spunem că acesta *rulează*.
, spunem

2020-10-06 16:55 UTC, razvand commented on chapters/basic/browser.rst
> +Putem opri browserul Firefox în mai multe moduri (așa cum am menționat în secțiunea :ref:`basic_start_stop_apps`)
două puncte la final

2020-10-06 16:55 UTC, razvand commented on chapters/basic/browser.rst
> +* Deschizând un terminal și tasând în terminal comanda de pornire (aici firefox), similar cu folosirea Alt+F2, ca în imaginea de mai jos:
tastând, nu tasând

`firefox` (format monotype)
`Alt+F2` (format monotype)

2020-10-06 16:55 UTC, razvand commented on chapters/basic/browser.rst
> +* Folosind combinația de taste ``Alt+F4`` care închide fereastra grafică, o scurtătură pentru folosirea butonului de închidere.
, care

2020-10-06 16:55 UTC, razvand commented on chapters/basic/browser.rst
> +După folosirea unei dintre metodele de mai sus, aplicația Firefox este oprită.
uneia

2020-10-06 16:55 UTC, razvand commented on chapters/basic/browser.rst
> +Pentru a accesa din nou aplicații web va trebui să repornim aplicația Firefox, folosind una dintre motodele din secțiunea :ref:`basic_start_browser`.
web,

2020-10-06 16:55 UTC, razvand commented on chapters/basic/browser.rst
> +În general avem cel puțin două variante pentru a face o acțiune:
În general,

2020-10-06 16:55 UTC, razvand commented on chapters/basic/browser.rst
> +#. Folosind combinația de taste din tastatură echivalente clickurilor
Folosind combinația de taste echivalentă clickurilor

2020-10-06 16:55 UTC, razvand commented on chapters/basic/browser.rst
> +Folosirea combinației de taste este mai rapidă, mai eficientă, dar necesită un efort de memorare din partea utilizatorului.
combinațiilor de taste

2020-10-06 16:55 UTC, razvand commented on chapters/basic/browser.rst
> +Dacă dorim să accesăm pagina web (*URL-ul*, *site-ul*, *linkul*) **google.com**, trebuie să introducem șirul ``www.google.com`` în bara de adrese.
fără www

2020-10-06 16:55 UTC, razvand commented on chapters/basic/browser.rst
> +Odată accesată bara de adrese putem introduce șirul www.google.com
fără www, pus cu monotype, punct la final

2020-10-06 16:55 UTC, razvand commented on chapters/basic/browser.rst
> +Spre exemplu, navigăm pe o rețea de socializare, am deschis un articol apărut în feed, l-am citit și acum vrem să revenim la feedul de pe rețeaua de socializare.
după ce am navigat ...

2020-10-06 16:55 UTC, razvand commented on chapters/basic/browser.rst
> +* Folosind butoanele **săgeată stânga** (*Go back one page*) și **săgeată dreapta** (*Go forward one page*) din interfața grafică a browserului ca în imaginea de mai jos:
, ca

2020-10-06 16:55 UTC, razvand commented on chapters/basic/browser.rst
> +Principalul motiv pentru care folosim browsere web este ca să vizualizăm content de pagini.
content -> conținut

2020-10-06 16:55 UTC, razvand commented on chapters/basic/browser.rst
> +Un caz pe care îl întâlnim des atunci când lucrăm cu un browser web este să avem mai multe pagini web deschise simultan.
web, este

2020-10-06 16:55 UTC, razvand commented on chapters/basic/browser.rst
> +Spre exemplu, avem nevoie să căutăm o informație pe Google cum ar fi *Cum gătim supă de pui acasă*.
Google,

2020-10-06 16:55 UTC, razvand commented on chapters/basic/browser.rst
> +Aplicația Firefox care rulează poate avea unul sau mai multe taburi pornite.
aflată în rulare

2020-10-06 16:55 UTC, razvand commented on chapters/basic/browser.rst
> +În sub-subsecțiunile următoare vom vorbi despre cum să deschidem, sa navigăm între taburi și să închidem taburi eficient.
Zi doar "subsecțiune". E prea mult "sub-subsecțiune".

2020-10-06 16:55 UTC, razvand commented on chapters/basic/browser.rst
> +În sub-subsecțiunile următoare vom vorbi despre cum să deschidem, sa navigăm între taburi și să închidem taburi eficient.
să deschidem taburi

2020-10-06 16:55 UTC, razvand commented on chapters/basic/browser.rst
> +* Folosind clickuri. Dăm click pe fiecare tab în parte ca în imaginea de mai jos:
, ca în

2020-10-06 16:55 UTC, razvand commented on chapters/basic/browser.rst
> +Să presupunem că vrem să găsim rețeta perfectă pentru supă de pui gătită în casă și vrem să deschidem mai multe rețete, fiecare într-un tab, pentru a le compara și a alege rețeta cea mai bună.
și pentru a alege

2020-10-06 16:55 UTC, razvand commented on chapters/basic/cheatsheet.rst
> +* Folosind iconuri ca în imaginea de mai jos:
, ca

2020-10-06 16:55 UTC, razvand commented on chapters/basic/cheatsheet.rst
> +* Folosind combinația de taste (*scurtătura*, *shortcutul*) ``Alt+F2`` și introducând șirul ``firefox`` ca în imaginea de mai jos:
, ca

2020-10-06 16:55 UTC, razvand commented on chapters/basic/cheatsheet.rst
> +* Folosind linia de comandă ca în imaginea de mai jos:
, ca

2020-10-06 16:55 UTC, razvand commented on chapters/basic/cheatsheet.rst
> +* Folosind clickuri ca în imaginea de mai jos:
, ca

2020-10-06 16:55 UTC, razvand commented on chapters/basic/cheatsheet.rst
> +* Folosind butoanele **săgeată stânga** (*Go back one page*) și **săgeată dreapta** (*Go forward one page*) din interfața grafică a browserului ca în imaginea de mai jos:
, ca

2020-10-06 16:55 UTC, razvand commented on chapters/basic/cheatsheet.rst
> +  Așa ne deplasăm în sus/jos cu câte o linie.
Fără "cu"

2020-10-06 16:55 UTC, razvand commented on chapters/basic/cheatsheet.rst
> +* Folosind butonul de remîprospătare (*refresh*) din browser ca în imaginea de mai jos:
, ca

2020-10-06 16:55 UTC, razvand commented on chapters/basic/cheatsheet.rst
> +* Folosind butonul cu simbolul ``+`` din interfața grafică a browserului ca în imaginea de mai jos:
, ca

2020-10-06 16:55 UTC, razvand commented on chapters/basic/cheatsheet.rst
> +* Folosind clickuri ca în imaginea de mai jos:
, ca

2020-10-06 16:55 UTC, razvand commented on chapters/basic/cheatsheet.rst
> +* Folosind butonul cu simbolul ``x`` din browser ca în imaginea de mai jos:
, ca

2020-10-06 16:55 UTC, razvand commented on chapters/basic/cheatsheet.rst
> +* Folosind clickuri. Folosim *click dreapta* pe link după care alegem opțiunea *Open Link in New Tab* din meniul contextual ca în imaginea de mai jos:
, ca

2020-10-06 16:55 UTC, razvand commented on chapters/basic/cheatsheet.rst
> +* Folosind iconuri ca în imaginea de mai jos:
, ca

2020-10-06 16:55 UTC, razvand commented on chapters/basic/cheatsheet.rst
> +* Folosind combinația de taste ``Alt+F2`` ca în imaginea de mai jos:
, ca

2020-10-06 16:55 UTC, razvand commented on chapters/basic/cheatsheet.rst
> +* Apăsând *click dreapta* și apoi butonul *Open Terminal* ca în imaginea de mai jos:
, ca

2020-10-06 16:55 UTC, razvand commented on chapters/basic/cheatsheet.rst
> +* Folosind butonul ``x`` din partea dreaptă-sus a aplicației ca în imaginea de mai jos:
, ca

2020-10-06 16:55 UTC, razvand commented on chapters/basic/cheatsheet.rst
> +* Folosind meniul aplicației ca în imaginea de mai jos:
, ca

2020-10-06 16:55 UTC, razvand commented on chapters/basic/cheatsheet.rst
> +  Apăsăm pe opțiunea *File* din meniu după care pe butonul *New Tab*.
, după care

2020-10-06 16:55 UTC, razvand commented on chapters/basic/cheatsheet.rst
> +* Apăsând *click dreapta* în interiorul terminalului după care pe butonul *New Tab* ca în imaginea de mai jos:
, după care  ... , ca

2020-10-06 16:55 UTC, razvand commented on chapters/basic/cheatsheet.rst
> +* Folosind meniul aplicației ca în imaginea de mai jos:
, ca

2020-10-06 16:55 UTC, razvand commented on chapters/basic/cheatsheet.rst
> +* Folosind butonul (*simbolul*) ``x`` din dreptul tabului ca în imaginea de mai jos:
, ca

2020-10-06 16:55 UTC, razvand commented on chapters/basic/cheatsheet.rst
> +* Folosind clickuri ca în imaginea de mai jos:
, ca

2020-10-06 16:55 UTC, razvand commented on chapters/basic/cheatsheet.rst
> +* Folosind combinația de taste ``Alt+<număr>`` unde *număr* este numărul (*indexul*) tabului la care vrem să ajungem.
, unde

2020-10-06 16:55 UTC, razvand commented on chapters/basic/cheatsheet.rst
> +* Folosind combinațiile de taste ``Ctrl+PageUp`` pentru a merge la următorul tab și ``Ctrl+PageDown`` pentru a trece la tabul anterior.
, pentru a trece la următorul tab, și ... , pentru a trece

Pe lângă virgule, folosește "trece" pentru consecvență.

2020-10-06 16:55 UTC, razvand commented on chapters/basic/cheatsheet.rst
> +* Folosind comanda ``clear`` în terminal ca în imaginea de mai jos:
, ca

2020-10-06 16:55 UTC, razvand commented on chapters/basic/cheatsheet.rst
> +* Selectăm textul, apăsăm *click dreapta* și apăsăm butonul *Copy* ca în imaginea de mai jos:
, ca

2020-10-06 16:55 UTC, razvand commented on chapters/basic/cheatsheet.rst
> +* Apăsăm *click dreapta* și apăsăm butonul *Paste* ca în imaginea de mai jos:
, ca

2020-10-06 16:55 UTC, razvand commented on chapters/basic/terminal.rst
> +Folosim linia de comandă prin intermediul aplicației *GNOME Terminal* care are identificatorul **gnome-terminal**.
, care

2020-10-06 16:55 UTC, razvand commented on chapters/basic/terminal.rst
> +* Apăsând *click dreapta* și apoi butonul *Open Terminal* ca în imaginea de mai jos:
, ca

2020-10-06 16:55 UTC, razvand commented on chapters/basic/terminal.rst
> +Ca să facem acest lucru putem să deschidem două terminale: unul cu aplicația pe care vrem să o monitorizăm și unul în care pornim aplicația de monitorizare.
lucru,

2020-10-06 16:55 UTC, razvand commented on chapters/basic/terminal.rst
> +Pe lângă aceste 2 acțiuni putem să avem nevoie să facem și altele, iar lucrul cu mai multe terminale deschise devine dificil.
2 acțiuni,

2020-10-06 16:55 UTC, razvand commented on chapters/basic/terminal.rst
> +În următoarele sub-subsecțiuni vom vorbi despre cum să deschidem, să închidem și să navigăm printre taburile din terminal.
s/printre/între/g

2020-10-06 16:55 UTC, razvand commented on chapters/basic/terminal.rst
> +Deschidem un nou tab atunci când avem nevoie să facem o altă operație fără a o întrerupe pe cea de acum.
, fără

2020-10-06 16:55 UTC, razvand commented on chapters/basic/terminal.rst
> +* Apăsând *click dreapta* în interiorul terminalului după care pe butonul *New Tab* ca în imaginea de mai jos:
, după care .... , ca

2020-10-06 16:55 UTC, razvand commented on chapters/basic/terminal.rst
> +* Folosind meniul aplicației ca în imaginea de mai jos:
, ca

2020-10-06 16:55 UTC, razvand commented on chapters/basic/terminal.rst
> +Vrem să navigăm printre taburile din terminal la fel ca în cazul browserului web pentru a putea trece de la o operație începută la alta rapid.
, la fel ca în cazul browserului web,

2020-10-06 16:55 UTC, razvand commented on chapters/basic/terminal.rst
> +* Folosind clickuri ca în imaginea de mai jos:
, ca

2020-10-06 16:55 UTC, razvand commented on chapters/basic/terminal.rst
> +* Folosind combinația de taste ``Alt+<număr>`` unde *număr* este numărul (*indexul*) tabului la care vrem să ajungem.
, unde

2020-10-06 16:55 UTC, razvand commented on chapters/basic/terminal.rst
> +  Combinațiile de taste folosite în terminal sunt similare cu cele din browser prezentare în secțiunea :ref:`basic_navigate_tabs_browser`.
, prezentate (virgulă și nu prezentare, ci prezentate)

2020-10-06 16:55 UTC, razvand commented on chapters/basic/terminal.rst
> +Pe lângă shortcuturile de pornire/oprire a terminalului, de lucru cu taburi în terminal, mai există și alte shortcuturi pe care dacă le reținem vom putea lucra în terminal foarte rapid.
cu care, dacă le reținem,

2020-10-06 16:55 UTC, razvand commented on chapters/basic/terminal.rst
> +În sub-subsecțiunile următoare vom vorbi despre scrollul, copierea și lipirea textului în terminal și despre golirea ecranului de terminal.
Doa subsecțiunile, nu sub-subsecțiunile

2020-10-06 16:55 UTC, razvand commented on chapters/basic/terminal.rst
> +Pentru golire ecranului de termninal avem mai multe variante:
golirea

2020-10-06 16:55 UTC, razvand commented on chapters/basic/terminal.rst
> +* Folosind comanda ``clear`` în terminal ca în imaginea de mai jos:
, ca

2020-10-06 16:55 UTC, razvand commented on chapters/basic/terminal.rst
> +* Selectăm textul, apăsăm *click dreapta* și apăsăm butonul *Copy* ca în imaginea de mai jos:
, ca

2020-10-06 16:55 UTC, razvand commented on chapters/basic/terminal.rst
> +* Apăsăm *click dreapta* și apăsăm butonul *Paste* ca în imaginea de mai jos:
, ca

2020-10-06 16:55 UTC, razvand commented on chapters/basic/workspace.rst
> +Putem să ajungem la un moment dat să avem foarte multe aplicații deschise simultan ca în imaginea de mai jos:
, ca

2020-10-06 16:55 UTC, razvand commented on chapters/basic/workspace.rst
> +* Folosind bara de aplicații (din stângă) ca în imaginea de mai jos:
, ca

2020-10-06 16:55 UTC, razvand commented on chapters/basic/workspace.rst
> +* Folosind combinația de taste ``Alt+Tab`` ca în imaginea de mai jos:
, ca

2020-10-06 16:55 UTC, razvand commented on chapters/basic/workspace.rst
> +Când avem prea multe aplicații deschise simultan, navigarea printre ele devine dificilă și consumatoare de timp.
s/printre/între

2020-10-06 16:55 UTC, razvand commented on chapters/basic/workspace.rst
> +Creăm workspace-urile descrise mai sus ca în imaginea de mai jos:
, ca

2020-10-06 16:55 UTC, razvand commented on chapters/basic/workspace.rst
> +#. Tragerea aplicației pe care vrem să o mutăm într-un nou workspace în partea dreaptă a ecranului.
, în partea ...

2020-10-06 17:24 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/22/merge

2020-10-06 17:25 UTC, merged