Add storage subsection for admin tasks chapter
Sergiu121/uso-lab-book pull request #37
Opened 2021-01-09 05:17 UTC by Sergiu121

2021-01-09 05:18 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/37/merge

2021-01-09 07:04 UTC, razvand requested changes
Îmi place. Am lăsat observații.

O observație care se aplică și la celelalte secțiuni: Găsește o denumire pentru stația locală și pentru stația remote (`local` / `remote` sau altceva) și definește-o de la bun început în capitol. Apoi folosește-o consecvent pe parcursul capitolului. Că acum folosești "stația curentă", "sistemul local", "stația de la distanță", "workstationul", "laptopul" și cauzează o confuzie.

Și când apare că se rulează o comandă sau se execută o acțiune, să fie clar unde se rulează: pe ``local`` sau ``remote``.

2021-01-09 07:04 UTC, razvand commented on chapters/task-admin/storage.rst
>  Dropbox este o soluție care se folosește de un server în Internet care stochează fișierele noastre, ca apoi acestea să fie replicate pe fiecare calculator client.
fără noastre

2021-01-09 07:04 UTC, razvand commented on chapters/task-admin/storage.rst
> +Este necesar să ne creăm un cont pentru a folosi serviciul Dropbox și să îl activăm.
Este necesară crearea și activarea unui cont pentru ...

2021-01-09 07:04 UTC, razvand commented on chapters/task-admin/storage.rst
> +Dropbox oferă o aplicație care rulează în linie de comandă pe care o vom descărca pentru a sincroniza sistemul de fișiere de pe serverele Dropbox într-un director local.
Unde o descărcăm? local, remote, să ai în vedere să precizezi asta

2021-01-09 17:51 UTC, Sergiu121 commented on chapters/task-admin/storage.rst
>  Soluția la această nevoie este să partajăm spațiul de stocare între serverul de la distanță și laptopul sau stația locală de pe care lucrăm.
Nu am în codul sursă, e ceva afișat prost de la GitHub.

2021-01-09 18:06 UTC, Sergiu121 commented on chapters/task-admin/storage.rst
> +Am scris în fișierul ``/etc/fstab`` folosind comanda ``echo``, iar pentru a monta sistemul de fișiere am folosit comanda ``mount`` cu opțiunea ``-a`` pentru montarea sistemelor de fișiere descrise în
Nu vreau să folosesc ``mount``. Am pus ``df``, ca să nu mai introduc alte comenzi noi.

2021-01-09 18:11 UTC, Sergiu121 commented on chapters/task-admin/storage.rst
> +Dropbox oferă o aplicație care rulează în linie de comandă pe care o vom descărca pentru a sincroniza sistemul de fișiere de pe serverele Dropbox într-un director local.
Se vede din promp că folosim ``uso``, nu?

2021-01-09 18:14 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/37/merge

2021-01-09 18:45 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/37/merge

2021-01-09 20:35 UTC, razvand commented on chapters/task-admin/storage.rst
> +Dropbox oferă o aplicație care rulează în linie de comandă pe care o vom descărca pentru a sincroniza sistemul de fișiere de pe serverele Dropbox într-un director local.
Nu e suficient. Spune și în text. Fă viața ușoară cititorului.

2021-01-09 21:24 UTC, razvand requested changes
Am adăugat recenzie.

2021-01-09 21:24 UTC, razvand commented on chapters/task-admin/storage.rst
> +    ``~/uso-lab/labs/10-tasks-admin/lab-containers/``.
O propoziție pe rând

2021-01-09 21:24 UTC, razvand commented on chapters/task-admin/storage.rst
> +    Infrastructura laboratorului este bazată pe containere docker ale căror
O propoziție pe rând

2021-01-09 21:24 UTC, razvand commented on chapters/task-admin/storage.rst
> +    După ce ați terminat de lucrat vă recomandăm să opriți containerele rulând
O propoziție pe rând

2021-01-09 21:24 UTC, razvand commented on chapters/task-admin/storage.rst
> +Soluția la această nevoie este să partajăm spațiul de stocare între serverul ``remote`` și ``local`` de pe care lucrăm.
și stația ``local``

2021-01-09 21:24 UTC, razvand commented on chapters/task-admin/storage.rst
> +Ca să montăm persistent sistemul de fișiere avem nevoie să copiem cheia SSH pe stația de la distanța, deoarece montarea se va face în mod neinteractiv, deci nu vom avea posibilitatea de a introduce p
distanță

2021-01-09 21:24 UTC, razvand commented on chapters/task-admin/storage.rst
> +Pentru a monta persistent sistemul de fișiere vom scrie o intrare în fișierul ``/etc/fstab`` care va conține detalii despre sistemul de fișiere pe care vrem să îl montăm.
, vom

2021-01-09 21:24 UTC, razvand commented on chapters/task-admin/storage.rst
> +SSHFS nu este o soluție bună pentru a face backup fișierelor deorece, existând o singură replică, ștergerea locală a unui fișier duce la ștergerea sa și de pe stația remote și, astfel, la pierderea s
deoarece

2021-01-09 21:24 UTC, razvand commented on chapters/task-admin/storage.rst
> +Aceste soluții sochează o replică a fișierului pe toate calculatoarele autentificate de pe un anumit cont.
stochează

2021-01-09 21:24 UTC, razvand commented on chapters/task-admin/storage.rst
> +Vom face asta accesând linkul afișat de aplicație.
asta -> acest lucru

2021-01-10 12:46 UTC, Sergiu121 commented on chapters/task-admin/storage.rst
> +Dropbox oferă o aplicație care rulează în linie de comandă pe care o vom descărca pentru a sincroniza sistemul de fișiere de pe serverele Dropbox într-un director local.
Oricum, am pus clarificare mai sus.

2021-01-10 12:55 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/37/merge

2021-01-10 16:39 UTC, razvand requested changes
Am adăugat o nouă recenzie.

2021-01-10 16:39 UTC, razvand commented on chapters/task-admin/storage.rst
> +    Pentru a descărca ultima versiune a repository-ului rulați comanda ``git pull`` în directorul ``~/uso-lab/labs/10-tasks-admin/lab-containers/``.
, rulați

2021-01-10 16:39 UTC, razvand commented on chapters/task-admin/storage.rst
> +    Dacă nu veți deja instalat Docker Engine pe sistem, scriptul ``~/uso-lab/labs/10-tasks-admin/lab-containers/lab_prepare.sh`` vă va instala aplicația.
veți -> aveți

2021-01-10 16:39 UTC, razvand commented on chapters/task-admin/storage.rst
> +Acest mod te montare a sistemului de fișier este temporară.
te -> de

fișier -> fișiere

2021-01-10 16:39 UTC, razvand commented on chapters/task-admin/storage.rst
> +Atunci când vom opri stația sistemul de fișiere va fi demontat.
stația,

2021-01-10 16:39 UTC, razvand commented on chapters/task-admin/storage.rst
> +Pentru a monta persistent sistemul de fișiere, vom scrie o intrare în fișierul ``/etc/fstab`` care va conține detalii despre sistemul de fișiere pe care vrem să îl montăm.
fstab, fișier care va ...

2021-01-10 16:39 UTC, razvand commented on chapters/task-admin/storage.rst
> +Am scris în fișierul ``/etc/fstab`` folosind comanda ``echo``, iar pentru a monta sistemul de fișiere am folosit comanda ``mount`` cu opțiunea ``-a`` pentru montarea sistemelor de fișiere descrise în
Pune un warnind de tipul "kids, do not try this at home. Folosiți editare interactivă, că altfel vă suprascrieți fișierul ``/etc/fstab``, pierdeți ce aveați deja acolo and all hell breaks loose."

2021-01-10 16:39 UTC, razvand commented on chapters/task-admin/storage.rst
> +Cu dezavantajul că trebuie configurate și riscul apariției conflictelor la modificări simultane pe noduri diferite.
și cu riscul

2021-01-10 16:39 UTC, razvand commented on chapters/task-admin/storage.rst
> +Pentru a descărca aplicația Dropbox, pe care o vom descărca folosind comanda ``wget`` și o vom instala folosind comanda ``dpkg`` împreună cu parametrul.
Ratezi predicatul principal din fraza de mai sus.

2021-01-10 16:39 UTC, razvand commented on chapters/task-admin/storage.rst
> +    Pentru a ne conecta la infrastructura pentru această secțiune vom folosi comanda ``./lab_prepare.sh connect dropbox``.
, vom folosi

2021-01-10 16:39 UTC, razvand commented on chapters/task-admin/storage.rst
> +#) Scrieți un fișier numit ``hello.txt`` mesajul ``Hello from remote`` de pe stația ``dropbox``.
Cum adică "de pe stația ``dropbox``"?

2021-01-10 16:39 UTC, razvand commented on chapters/task-admin/storage.rst
> +Verificați conținutul fișierului de pe stația ``uso``.
De ce "de pe" și nu "pe"

2021-01-10 16:39 UTC, razvand commented on chapters/task-admin/storage.rst
>  Extra: Stocarea partajată folosind un server privat
TODO aici

2021-01-10 16:45 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/37/merge

2021-01-10 17:32 UTC, Sergiu121 commented on chapters/task-admin/storage.rst
> +Am scris în fișierul ``/etc/fstab`` folosind comanda ``echo``, iar pentru a monta sistemul de fișiere am folosit comanda ``mount`` cu opțiunea ``-a`` pentru montarea sistemelor de fișiere descrise în
Nici nu am văzut că am lăsat făra apendare. Am modificat și am zis și de editor.

2021-01-10 17:37 UTC, Sergiu121 commented on chapters/task-admin/storage.rst
> +#) Scrieți un fișier numit ``hello.txt`` mesajul ``Hello from remote`` de pe stația ``dropbox``.
Am clarificat.

2021-01-10 20:16 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/37/merge

2021-01-10 21:35 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/37/merge

2023-09-11 19:44 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/37/merge

2025-12-17 11:41 UTC, merged