security:data: TODO
Sergiu121/uso-lab-book pull request #55
Opened 2021-08-12 11:13 UTC by CostinCarabas

Signed-off-by: Costin Carabas <costin.carabas@gmail.com>

2021-08-30 09:39 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/55/merge

2021-08-30 10:01 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/55/merge

2022-09-30 13:26 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/55/merge

2022-10-07 14:13 UTC, edi33416 requested changes

2023-08-24 15:09 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/55/merge

2023-08-24 15:11 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/55/merge

2023-08-25 13:05 UTC, Sergiu121 commented
Published at http://sergiu121.github.io/refs/pull/55/merge

2023-09-11 14:51 UTC, edi33416 reviewed
câteva observații

2023-09-11 14:51 UTC, edi33416 commented on chapters/security/data.rst
> +Așa cum am precizat mai sus, în cazul acestor permisiuni, utilizatorii și procesele lor sunt subiecții, iar fișierele sunt obiectele.
```suggestion
În cazul acestor permisiuni, utilizatorii și procesele lor sunt subiecții, iar fișierele sunt obiectele.
```

2023-09-11 14:51 UTC, edi33416 commented on chapters/security/data.rst
> +Observăm din eroarea primită din partea sistemului că pentru a schimba deținătorul unui fișier este nevoie de drepturi privilegiate.
Aș sparge code-block-ul în două și aș pune observația asta fix după eroare. Apoi aș pune comanda cu sudo și explicația pentru ea. Altfel, îmi este că nici nu vor observa prima eroare (cum trec peste și la lab)

2023-09-11 14:51 UTC, edi33416 commented on chapters/security/data.rst
> +Observăm că pentru a scoate permisiunile de citire, pentru toate cele trei categorii (user, group, others), folosim opțiunea (flagul)  *-r*, după care fișierul/directorul țintă.
adaugă aici faptul că `-` este minus ca în fără permisiunea de read. Lafel de bine puteau folosi `+w` pentru a adăuga write. Simt că o să ajute să nu fie confuzii cu -R pentru recursiv (ceea ce spui mai jos, dar și mie mi-a luat puțin să-mi dau seama la ce se referea paragraful de mai jos)

2023-09-11 14:51 UTC, edi33416 commented on chapters/security/data.rst
> +În această situație, permisiunile pe fișiere în sistemul local sunt nerelevante pentru un atacator care poate să captureze datele când sunt transferate.
```suggestion
În această situație, permisiunile pe fișiere în sistemul local sunt nerelevante pentru un atacator care poate să captureze datele atunci când sunt transferate.
```

2023-09-11 14:51 UTC, edi33416 commented on chapters/security/data.rst
> +În această situație, permisiunile pe fișiere în sistemul local sunt nerelevante pentru un atacator care poate să captureze datele când sunt transferate.
sau "în timpul transferului"

2023-09-11 14:51 UTC, edi33416 commented on chapters/security/data.rst
> +De aceea avem nevoie de moduri de a ascunde aceste date astfel încât, chiar capturate, să nu fie citite de un atacator, adică să păstrăm *confidențialitatea datelor*. *Confidențialitatea datelor* est
```suggestion
De aceea avem nevoie de moduri de a ascunde aceste date astfel încât, chiar capturate, să nu poată fi citite de un atacator, adică să păstrăm *confidențialitatea datelor*. *Confidențialitatea datelor* este asigurată, în general, prin *criptare*.
```

2023-09-11 14:51 UTC, edi33416 commented on chapters/security/data.rst
> +De aceea avem nevoie de moduri de a ascunde aceste date astfel încât, chiar capturate, să nu fie citite de un atacator, adică să păstrăm *confidențialitatea datelor*. *Confidențialitatea datelor* est
cred că aș scoate acel "în general". Confidențialitatea e prin criptare

2023-09-11 14:51 UTC, edi33416 commented on chapters/security/data.rst
> +    0000000: 5361 6c74 6564 5f5f 2562 0ad0 cc5c 7969  Salted__%b...\yi
câteva cuvinte despre ce-i un salt? Au asta în output-ul xxd

2023-09-11 14:51 UTC, edi33416 commented on chapters/security/data.rst
> +Mai mult, observăm că la introducerea unui nou caracter **!**, suma de control este complet diferită.
întărește ultima afirmație: un hash bun trebuie să producă un rezultat foarte diferit, chiar dacă diferențele sunt mici

2023-09-11 15:16 UTC, lizababu requested changes

2023-09-11 15:16 UTC, lizababu commented on chapters/security/data.rst
> +    student@uso-demo:~/securitate/stocks$ chown Amazon:Amazon Amazon
Does the `Amazon` user and group exist on the WM, or is it created in previously? Otherwise this will raise an error.

2023-09-11 15:16 UTC, lizababu commented on chapters/security/data.rst
> +Observăm că *ffe3ae3af537e5dd8999c86e54ac513e* este suma de control pentru *FAANG is the place to be*.
```suggestion
Observăm că *ffe3ae3af537e5dd8999c86e54ac513e* este suma de control pentru *FAANG is the place to be\n*.
```
Or add the `-n` to `echo` so it's not confusing for readers (they might try an online md5sum and they will get a different output).

2025-12-17 11:46 UTC, merged